import { readFile } from 'node:fs/promises'
import { test } from 'node:test'
import assert from 'node:assert/strict'

const readConsole = () => readFile(new URL('./public/index.html', import.meta.url), 'utf8')

test('console exposes one plan-first Agent Company workspace', async () => {
  const html = await readConsole()
  assert.match(html, /data-view="company"/)
  assert.match(html, /id="view-company"/)
  assert.match(html, /api\('GET','\/api\/agent-company'\)/)
  assert.match(html, /api\('POST','\/api\/agent-company',\{action:'plan',\.\.\.input\}\)/)
  assert.match(html, /I reviewed this exact client, evidence, assignments, and budget/)
  assert.match(html, /id="companyQueueButton" type="button" disabled/)
  assert.match(html, /if\(companyDraft\)invalidateCompanyPlan\('Inputs changed\. Plan the cycle again\.'\)/)
  assert.match(html, /if\(location\.hash==='\#company'\)/)
  assert.match(html, /companyRoster=\[\]\s+companyWorkOrders=\[\]\s+companyOperations=null\s+companyOpenWorkOrder=null\s+resetCompanyRosterTools\(\)\s+invalidateCompanyPlan\(\)/)
  assert.doesNotMatch(html, /id="companyRunButton"|action:'run',\.\.\.companyDraft\.input/)
})

test('Agent Company console queues, dispatches, and proves exact reviewed work orders', async () => {
  const html = await readConsole()
  assert.match(html, /action:'work-order-create',\.\.\.companyDraft\.input/)
  assert.match(html, /action:'work-order-list',clientId,limit:20/)
  assert.match(html, /action:'work-order-get',clientId,workOrderId/)
  assert.match(html, /action:'work-order-run',clientId:order\.clientId,workOrderId:order\.workOrderId,planHash:order\.planHash,confirmation:`RUN \$\{order\.workOrderId\}`/)
  assert.match(html, /I reviewed this stored plan, evidence fingerprints, assignments, and budget/)
  assert.match(html, /Work order queued\. No model call was made\./)
  assert.match(html, /renderCompanyWorkOrderDetail\(response\.workOrder\)/)
  assert.match(html, /action:'work-order-proof',clientId:order\.clientId,workOrderId:order\.workOrderId/)
  assert.match(html, /action:'work-order-review',clientId:order\.clientId,workOrderId:order\.workOrderId,resultHash:order\.resultHash/)
  assert.match(html, /action:'work-order-cancel',clientId:order\.clientId,workOrderId:order\.workOrderId,planHash:order\.planHash/)
  assert.match(html, /confirmation:`CANCEL AND SCRUB \$\{order\.workOrderId\} \$\{order\.planHash\}`/)
  assert.match(html, /syncCompanyWorkOrderList\(response\.workOrder\)\s+renderCompanyWorkOrderDetail\(response\.workOrder\)/)
  assert.match(html, /decision==='accepted'\?'ACCEPT':'REQUEST CHANGES'/)
  assert.match(html, /Download proof packet/)
  assert.match(html, /Record immutable review/)
  assert.match(html, /Operator-recorded evidence only\. This is not a customer login or digital signature\./)
  assert.match(html, /customer authentication: no/)
  assert.match(html, /I copied the exact decision and statement from the selected source/)
  assert.match(html, /Permanently cancel this order and scrub its queued source evidence/)
  assert.match(html, /Work order cancelled\. Queued source evidence was scrubbed\./)
  assert.match(html, /order\.evidenceState==='scrubbed'\?'evidence scrubbed':'evidence retained'/)
  assert.doesNotMatch(html, /value="internal">Internal review/)
  assert.match(html, /companyWorkOrders=\[\]\s+companyOperations=null\s+companyOpenWorkOrder=null/)
  assert.match(html, /invalidateCompanyPlan\(\)\s+\$\('#companyOrderDetail'\)\.hidden=true\s+\$\('#companyOrderDetail'\)\.innerHTML=''\s+\$\('#companyResults'\)\.innerHTML=''/)
  assert.doesNotMatch(html, /order\.input|workOrder\.input/)
})

test('Agent Company console measures and immutably evaluates terminal work without output exposure', async () => {
  const html = await readConsole()
  assert.match(html, /id="companyOperationsTitle">Company health/)
  assert.match(html, /Measured work-order evidence, not a customer SLA/)
  assert.match(html, /action:'operations-report',clientId,windowDays/)
  assert.match(html, /action:'work-order-evaluate',clientId:order\.clientId,workOrderId:order\.workOrderId,planHash:order\.planHash,verdict,checks,confirmation:`EVALUATE \$\{order\.workOrderId\}`/)
  assert.match(html, /Record one immutable, checklist-only internal verdict/)
  assert.match(html, /data-company-evaluation-check="accurate"/)
  assert.match(html, /data-company-evaluation-check="complete"/)
  assert.match(html, /data-company-evaluation-check="usable"/)
  assert.match(html, /data-company-evaluation-check="boundarySafe"/)
  assert.match(html, /direct compatibility cycles are excluded/)
  assert.match(html, /Workforce utilization/)
  assert.match(html, /Assignment metadata only; specialist outputs stay private/)
  assert.match(html, /workforce\.availableAgents/)
  assert.match(html, /agent\.usedRoleCalls/)
  assert.match(html, /cancelled excluded from delivery metrics/)
  assert.doesNotMatch(html, /companyEvaluationNotes|evaluationNotes|evaluation\.output/i)
})

test('Agent Company roster remains usable as the fixed workforce expands', async () => {
  const html = await readConsole()
  assert.match(html, /id="companyRosterSearch" type="search"/)
  assert.match(html, /id="companyDepartmentFilter"/)
  assert.match(html, /agent\.evidenceHint/)
  assert.match(html, /function applyCompanyRosterFilter\(\)/)
  assert.match(html, /row\.hidden=\!\(matchesText&&matchesDepartment\)&&\!checked/)
  assert.match(html, /companyRosterSearch'\)\.addEventListener\('input',applyCompanyRosterFilter\)/)
})

test('Agent Company UI accepts bounded evidence but no credential or action fields', async () => {
  const html = await readConsole()
  const panel = html.match(/<section id="view-company"[\s\S]*?<section id="view-workcells"/)?.[0] || ''
  assert.ok(panel)
  assert.match(panel, /id="companyRoleBudget" type="number" min="1" max="8"/)
  assert.match(html, /data-company-check type="checkbox"/)
  assert.match(html, /data-company-evidence maxlength="12000"[^>]* disabled/)
  assert.match(html, /\.company-agent:not\(\.selected\) \.company-evidence\{display:none\}/)
  assert.doesNotMatch(panel, /type="password"|name="[^"]*(?:secret|token|key)|Apply|Execute|Send/i)
  assert.doesNotMatch(html, /setInterval\(loadCompanyAgents|eval\s*\(/)
})

test('Agent Company controls remain touch-safe and collapse to one column', async () => {
  const html = await readConsole()
  assert.match(html, /\.key\{max-width:180px;min-height:44px\}/)
  assert.match(html, /nav button\{min-height:44px/)
  assert.match(html, /\.company-agent-choice\{[^}]*min-height:44px/)
  assert.match(html, /\.company-confirm\{[^}]*min-height:44px/)
  assert.match(html, /\.company-actions button\{min-height:44px\}/)
  assert.match(html, /\.company-plan-actions button\{min-height:44px\}/)
  assert.match(html, /\.company-new-cycle\{min-height:44px\}/)
  assert.match(html, /\.company-work-orders-head button\{min-height:44px\}/)
  assert.match(html, /\.company-order-actions button,\.company-cancel-actions button\{min-height:44px\}/)
  assert.match(html, /\.company-order-confirm\{[^}]*min-height:44px/)
  assert.match(html, /\.company-review-actions button\{min-height:44px/)
  assert.match(html, /\.company-review-fields input,\.company-review-fields select\{min-height:44px/)
  assert.match(html, /\.company-operations-controls select,\.company-operations-controls button\{min-height:44px/)
  assert.match(html, /\.company-evaluation-check\{[^}]*min-height:44px/)
  assert.match(html, /\.company-roster-tools input,\.company-roster-tools select\{min-height:44px/)
  assert.match(html, /\.company-workforce-row\{[^}]*min-height:44px/)
  assert.match(html, /\.company-evaluation-confirm\{[^}]*min-height:44px/)
  assert.match(html, /\.company-agent\{grid-template-columns:1fr\}/)
  assert.match(html, /\.company-scope\{grid-template-columns:1fr\}/)
  assert.match(html, /\.company-assignment,\.company-order-row,\.company-target\{grid-template-columns:1fr/)
  assert.match(html, /\.company-health-summary\{grid-template-columns:1fr\}/)
  assert.match(html, /\.company-evaluation-grid\{grid-template-columns:1fr\}/)
  assert.match(html, /\.company-roster-tools\{grid-template-columns:1fr\}/)
  assert.match(html, /\.company-workforce-row\{grid-template-columns:1fr/)
  assert.match(html, /\.company-toolbar,\.company-plan,\.company-results,\.company-operations,\.company-order-detail\{scroll-margin-top:160px\}/)
  assert.match(html, /\.company-scope \.field:last-child,\.company-review-fields \.statement\{grid-column:1\}/)
  assert.match(html, /\.company-order-actions,\.company-cancel-actions,\.company-review-actions\{align-items:stretch;flex-direction:column\}/)
})

test('Agent Company API route is a dedicated function before the catch-all', async () => {
  const config = JSON.parse(await readFile(new URL('./vercel.json', import.meta.url), 'utf8'))
  assert.equal(config.functions['api/agent-company.mjs'].maxDuration, 60)
  const companyRoute = config.routes.findIndex((route) => route.src === '/api/agent-company')
  const catchAll = config.routes.findIndex((route) => route.src === '/api/(.*)')
  assert.ok(companyRoute >= 0 && companyRoute < catchAll)
  const localServer = await readFile(new URL('./console/server.mjs', import.meta.url), 'utf8')
  assert.match(localServer, /import \{ handleAgentCompany \} from '\.\.\/api\/agent-company\.mjs'/)
  assert.match(localServer, /url\.pathname === '\/api\/agent-company'\s*\? await handleAgentCompany\(request\)\s*:\s*await handle\(request\)/)
  assert.match(localServer, /requested === '\/status'/)
  assert.match(localServer, /target\.startsWith\(`\$\{publicRoot\}\$\{sep\}`\)/)
  assert.match(localServer, /CONTENT_TYPES\[extname\(target\)\]/)
})

test('console inline scripts parse after Agent Company wiring', async () => {
  const html = await readConsole()
  const scripts = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map((match) => match[1])
  assert.ok(scripts.length)
  for (const source of scripts) assert.doesNotThrow(() => new Function(source))
})
