import { readFile } from 'node:fs/promises'
import { test } from 'node:test'
import assert from 'node:assert/strict'

const readConsole = () => readFile(new URL('./public/index.html', import.meta.url), 'utf8')

test('console exposes one plan-first Agent Company workspace', async () => {
  const html = await readConsole()
  assert.match(html, /data-view="company"/)
  assert.match(html, /id="view-company"/)
  assert.match(html, /api\('GET','\/api\/agent-company'\)/)
  assert.match(html, /api\('POST','\/api\/agent-company',\{action:'plan',\.\.\.input\}\)/)
  assert.match(html, /I reviewed this exact client, evidence, assignments, and budget/)
  assert.match(html, /id="companyQueueButton" type="button" disabled/)
  assert.match(html, /if\(companyDraft\)invalidateCompanyPlan\('Inputs changed\. Plan the cycle again\.'\)/)
  assert.match(html, /if\(location\.hash==='\#company'\)/)
  assert.match(html, /companyRoster=\[\]\s+companyWorkOrders=\[\]\s+companyOperations=null\s+companyOpenWorkOrder=null\s+companyMissions=\[\]\s+companyOpenMission=null\s+resetCompanyRosterTools\(\)\s+invalidateCompanyPlan\(\)/)
  assert.doesNotMatch(html, /id="companyRunButton"|action:'run',\.\.\.companyDraft\.input/)
})

test('Agent Company console queues, dispatches, and proves exact reviewed work orders', async () => {
  const html = await readConsole()
  assert.match(html, /action:'work-order-create',\.\.\.companyDraft\.input/)
  assert.match(html, /action:'work-order-list',clientId,limit:20/)
  assert.match(html, /action:'work-order-get',clientId,workOrderId/)
  assert.match(html, /action:'work-order-run',clientId:order\.clientId,workOrderId:order\.workOrderId,planHash:order\.planHash,confirmation:`RUN \$\{order\.workOrderId\}`/)
  assert.match(html, /I reviewed this stored plan, evidence fingerprints, assignments, and budget/)
  assert.match(html, /Work order queued\. No model call was made\./)
  assert.match(html, /renderCompanyWorkOrderDetail\(response\.workOrder\)/)
  assert.match(html, /action:'work-order-proof',clientId:order\.clientId,workOrderId:order\.workOrderId/)
  assert.match(html, /action:'work-order-review',clientId:order\.clientId,workOrderId:order\.workOrderId,resultHash:order\.resultHash/)
  assert.match(html, /action:'work-order-cancel',clientId:order\.clientId,workOrderId:order\.workOrderId,planHash:order\.planHash/)
  assert.match(html, /confirmation:`CANCEL AND SCRUB \$\{order\.workOrderId\} \$\{order\.planHash\}`/)
  assert.match(html, /syncCompanyWorkOrderList\(response\.workOrder\)\s+renderCompanyWorkOrderDetail\(response\.workOrder\)/)
  assert.match(html, /decision==='accepted'\?'ACCEPT':'REQUEST CHANGES'/)
  assert.match(html, /Download proof packet/)
  assert.match(html, /Record immutable review/)
  assert.match(html, /Operator-recorded evidence only\. This is not a customer login or digital signature\./)
  assert.match(html, /customer authentication: no/)
  assert.match(html, /I copied the exact decision and statement from the selected source/)
  assert.match(html, /Permanently cancel this order and scrub its queued source evidence/)
  assert.match(html, /Work order cancelled\. Queued source evidence was scrubbed\./)
  assert.match(html, /order\.evidenceState==='scrubbed'\?'evidence scrubbed':'evidence retained'/)
  assert.doesNotMatch(html, /value="internal">Internal review/)
  assert.match(html, /companyWorkOrders=\[\]\s+companyOperations=null\s+companyOpenWorkOrder=null/)
  assert.match(html, /invalidateCompanyPlan\(\)\s+resetCompanyPlaybooks\(\)\s+\$\('#companyOrderDetail'\)\.hidden=true\s+\$\('#companyOrderDetail'\)\.innerHTML=''\s+\$\('#companyResults'\)\.innerHTML=''/)
  assert.doesNotMatch(html, /order\.input|workOrder\.input/)
})

test('Agent Company console measures and immutably evaluates terminal work without output exposure', async () => {
  const html = await readConsole()
  assert.match(html, /id="companyOperationsTitle">Company health/)
  assert.match(html, /Measured work-order evidence, not a customer SLA/)
  assert.match(html, /action:'operations-report',clientId,windowDays/)
  assert.match(html, /action:'work-order-evaluate',clientId:order\.clientId,workOrderId:order\.workOrderId,planHash:order\.planHash,verdict,checks,confirmation:`EVALUATE \$\{order\.workOrderId\}`/)
  assert.match(html, /Record one immutable, checklist-only internal verdict/)
  assert.match(html, /data-company-evaluation-check="accurate"/)
  assert.match(html, /data-company-evaluation-check="complete"/)
  assert.match(html, /data-company-evaluation-check="usable"/)
  assert.match(html, /data-company-evaluation-check="boundarySafe"/)
  assert.match(html, /direct compatibility cycles are excluded/)
  assert.match(html, /Workforce utilization/)
  assert.match(html, /Assignment metadata only; specialist outputs stay private/)
  assert.match(html, /workforce\.availableAgents/)
  assert.match(html, /agent\.usedRoleCalls/)
  assert.match(html, /cancelled excluded from delivery metrics/)
  assert.doesNotMatch(html, /companyEvaluationNotes|evaluationNotes|evaluation\.output/i)
})

test('Agent Company roster remains usable as the fixed workforce expands', async () => {
  const html = await readConsole()
  assert.match(html, /id="companyRosterSearch" type="search"/)
  assert.match(html, /id="companyDepartmentFilter"/)
  assert.match(html, /agent\.evidenceHint/)
  assert.match(html, /function applyCompanyRosterFilter\(\)/)
  assert.match(html, /row\.hidden=\!\(matchesText&&matchesDepartment\)&&\!checked/)
  assert.match(html, /companyRosterSearch'\)\.addEventListener\('input',applyCompanyRosterFilter\)/)
})

test('Agent Company console persists staged delegation with server-verified mission gates', async () => {
  const html = await readConsole()
  assert.match(html, /id="companyPlaybookTitle">Delegate a business outcome/)
  assert.match(html, /id="companyPlaybookSelect" required disabled/)
  assert.match(html, /id="companyMissionId"[^>]*\{0,59\}/)
  assert.match(html, /action:'playbook-plan',clientId,missionId,playbookId/)
  assert.match(html, /Fixed stages, reviewed handoffs, and one explicit work order at a time/)
  assert.match(html, /id="companyMissionsTitle">Durable missions/)
  assert.match(html, /I reviewed this exact mission, ordered stages, agents, role budgets, and handoff gates/)
  assert.match(html, /action:'mission-create',clientId,missionId,playbookId/)
  assert.match(html, /action:'mission-list',clientId,limit:10/)
  assert.match(html, /action:'mission-get',clientId,missionRunId/)
  assert.match(html, /stage\.status==='ready'\?\(companyCan\('mission-stage-queue'\)\?`<button data-company-mission-prepare=/)
  assert.match(html, /companyPreparedPlaybookStage=\{\.\.\.stage,missionRunId:mission\.missionRunId,missionPlanHash:mission\.planHash\}/)
  assert.match(html, /\$\('#companyCycleId'\)\.value=stage\.cycleId/)
  assert.match(html, /\$\('#companyRoleBudget'\)\.value=String\(stage\.roleBudget\)/)
  assert.match(html, /Stage \$\{stage\.number\} prepared\. Add only its approved evidence/)
  assert.match(html, /action:'mission-stage-queue',clientId:companyDraft\.input\.clientId,missionRunId:stage\.missionRunId,missionPlanHash:stage\.missionPlanHash,stageId:stage\.stageId,evidence,confirmation:`QUEUE/)
  assert.match(html, /action:'mission-stage-advance',clientId:mission\.clientId,missionRunId:mission\.missionRunId,missionPlanHash:mission\.planHash/)
  assert.match(html, /The server will verify the exact terminal result and accepted immutable evaluation before changing mission state\./)
  assert.match(html, /rawHandoffsStored\?'yes':'no, fingerprints only'/)
  assert.match(html, /companyPlaybookPlan=null\s+clearPreparedCompanyStage\(\)\s+\$\('#companyPlaybookPlan'\)\.hidden=true\s+\$\('#companyPlaybookState'\)\.textContent='Client changed\. Plan delegation again\.'/)
  assert.doesNotMatch(html, /Previous stage has an accepted evaluation and I reviewed the redacted handoff|data-company-playbook-gate|button\.disabled=!gate\.checked/)
  assert.doesNotMatch(html, /action:'playbook-run'|automaticDispatch:true|dynamicDelegation:true|crossStageContext:true/)
})

test('Agent Company console uses one-time tenant sessions without persisting the owner key', async () => {
  const html = await readConsole()
  assert.match(html, /id="companyAccessTitle">Workspace access/)
  assert.match(html, /#view-company\.company-locked>:not\(\.company-toolbar\):not\(\.company-access\)\{display:none!important\}/)
  assert.match(html, /id="companySignInCode" autocomplete="one-time-code"[^>]*maxlength="20"/)
  assert.match(html, /id="companyInviteClientId"[^>]*required/)
  assert.match(html, /id="companyInviteOperatorId"[^>]*required/)
  assert.match(html, /id="companyInviteRole"[^>]*><option value="operator">Operator<\/option><option value="reviewer">Reviewer<\/option><option value="viewer">Viewer<\/option>/)
  assert.match(html, /fetch\('\/api\/agent-company-auth',\{method,credentials:'same-origin'/)
  assert.match(html, /'x-supermega-company-request':'1'/)
  assert.match(html, /action:'exchange-code',code/)
  assert.match(html, /action:'issue-code'/)
  assert.match(html, /id="companyAccessAdmin"[^>]*hidden/)
  assert.match(html, /id="companyAccessRefresh" type="button">Refresh/)
  assert.match(html, /action:'list-access',clientId/)
  assert.match(html, /action:'revoke-access',clientId:companyAccessClientId\(\),accessType,accessId/)
  assert.match(html, /confirm\(`Revoke \$\{accessType\} access for \$\{operatorId\}\?`\)/)
  assert.match(html, /data-company-access-revoke=/)
  assert.match(html, /companyAuthFetch\('DELETE'\)/)
  assert.match(html, /sessionStorage\.getItem\('sm\.owner'\)/)
  assert.match(html, /sessionStorage\.setItem\('sm\.owner',key\)/)
  assert.match(html, /localStorage\.removeItem\('sm\.ops'\)/)
  assert.doesNotMatch(html, /localStorage\.setItem\('sm\.(?:ops|owner)'/)
  assert.match(html, /const companyCan=\(action\)=>Boolean\(companyAuth/)
  assert.match(html, /\(companyAuth\.allowedActions\|\|\[\]\)\.some\(value=>value==='\*'\|\|value===action\)/)
  assert.match(html, /\$\('#companyClientId'\)\.readOnly=true/)
  assert.match(html, /\$\('#view-company'\)\.classList\.toggle\('company-locked',!signedIn\)/)
  assert.doesNotMatch(html, /companyAccessInventory\.(?:tokenDigest|planHash|sessionToken)|entry\.(?:tokenDigest|planHash|sessionToken)/)
  assert.doesNotMatch(html, /Enter the ops passcode|Agent solution/)
})

test('Agent Company UI accepts bounded evidence but no credential or action fields', async () => {
  const html = await readConsole()
  const panel = html.match(/<section id="view-company"[\s\S]*?<section id="view-workcells"/)?.[0] || ''
  assert.ok(panel)
  assert.match(panel, /id="companyRoleBudget" type="number" min="1" max="8"/)
  assert.match(html, /data-company-check type="checkbox"/)
  assert.match(html, /data-company-evidence[^>]*maxlength="12000"[^>]* disabled/)
  assert.match(html, /\.company-agent:not\(\.selected\) \.company-evidence\{display:none\}/)
  assert.doesNotMatch(panel, /type="password"|name="[^"]*(?:secret|token|key)|Apply|Execute|Send/i)
  assert.doesNotMatch(html, /setInterval\(loadCompanyAgents|eval\s*\(/)
})

test('Agent Company controls remain touch-safe and collapse to one column', async () => {
  const html = await readConsole()
  assert.match(html, /\[hidden\]\{display:none!important\}/)
  assert.match(html, /\.key\{max-width:180px;min-height:44px\}/)
  assert.match(html, /nav button\{min-height:44px/)
  assert.match(html, /\.company-agent-choice\{[^}]*min-height:44px/)
  assert.match(html, /\.company-confirm\{[^}]*min-height:44px/)
  assert.match(html, /\.company-actions button\{min-height:44px\}/)
  assert.match(html, /\.company-plan-actions button\{min-height:44px\}/)
  assert.match(html, /\.company-new-cycle\{min-height:44px\}/)
  assert.match(html, /\.company-work-orders-head button\{min-height:44px\}/)
  assert.match(html, /\.company-order-actions button,\.company-cancel-actions button\{min-height:44px\}/)
  assert.match(html, /\.company-order-confirm\{[^}]*min-height:44px/)
  assert.match(html, /\.company-review-actions button\{min-height:44px/)
  assert.match(html, /\.company-review-fields input,\.company-review-fields select\{min-height:44px/)
  assert.match(html, /\.company-operations-controls select,\.company-operations-controls button\{min-height:44px/)
  assert.match(html, /\.company-evaluation-check\{[^}]*min-height:44px/)
  assert.match(html, /\.company-roster-tools input,\.company-roster-tools select\{min-height:44px/)
  assert.match(html, /\.company-workforce-row\{[^}]*min-height:44px/)
  assert.match(html, /\.company-evaluation-confirm\{[^}]*min-height:44px/)
  assert.match(html, /\.company-playbook-fields select,\.company-playbook-fields input,\.company-playbook-fields button\{min-height:44px\}/)
  assert.match(html, /\.company-playbook-stage-actions button\{min-height:44px/)
  assert.match(html, /\.company-playbook-create button\{min-height:44px\}/)
  assert.match(html, /\.company-missions-head button\{min-height:44px\}/)
  assert.match(html, /\.company-mission-advance-actions button\{min-height:44px\}/)
  assert.match(html, /\.company-access-form input,\.company-access-form select,\.company-access-form button\{min-height:44px\}/)
  assert.match(html, /\.company-invite-fields input,\.company-invite-fields select,\.company-invite-fields button\{min-height:44px\}/)
  assert.match(html, /\.company-access-admin-head button\{min-height:44px\}/)
  assert.match(html, /\.company-access-row\{[^}]*min-height:60px/)
  assert.match(html, /\.company-access-row button\{min-height:44px/)
  assert.match(html, /\.company-access-head \.badge\{align-self:flex-start\}/)
  assert.match(html, /\.company-agent\{grid-template-columns:1fr\}/)
  assert.match(html, /\.company-scope\{grid-template-columns:1fr\}/)
  assert.match(html, /\.company-assignment,\.company-mission-row,\.company-order-row,\.company-target\{grid-template-columns:1fr/)
  assert.match(html, /\.company-health-summary\{grid-template-columns:1fr\}/)
  assert.match(html, /\.company-evaluation-grid\{grid-template-columns:1fr\}/)
  assert.match(html, /\.company-roster-tools\{grid-template-columns:1fr\}/)
  assert.match(html, /\.company-workforce-row\{grid-template-columns:1fr/)
  assert.match(html, /\.company-toolbar,\.company-playbook-plan,\.company-plan,\.company-results,\.company-operations,\.company-order-detail\{scroll-margin-top:160px\}/)
  assert.match(html, /\.activation-fields,\.owner-evidence-fields,\.company-access-form,\.company-invite-fields,\.company-playbook-fields,\.company-scope\{grid-template-columns:1fr\}/)
  assert.match(html, /\.company-access-row\{grid-template-columns:1fr;gap:5px\}/)
  assert.match(html, /\.company-access-row button\{width:100%\}/)
  assert.match(html, /\.company-playbook-stage\{grid-template-columns:34px minmax\(0,1fr\)/)
  assert.match(html, /\.company-scope \.field:last-child,\.company-review-fields \.statement\{grid-column:1\}/)
  assert.match(html, /\.company-order-actions,\.company-cancel-actions,\.company-review-actions\{align-items:stretch;flex-direction:column\}/)
})

test('Agent Company API route is a dedicated function before the catch-all', async () => {
  const config = JSON.parse(await readFile(new URL('./vercel.json', import.meta.url), 'utf8'))
  assert.equal(config.functions['api/agent-company-auth.mjs'].maxDuration, 15)
  assert.equal(config.functions['api/agent-company.mjs'].maxDuration, 60)
  const authRoute = config.routes.findIndex((route) => route.src === '/api/agent-company-auth')
  const companyRoute = config.routes.findIndex((route) => route.src === '/api/agent-company')
  const catchAll = config.routes.findIndex((route) => route.src === '/api/(.*)')
  assert.ok(authRoute >= 0 && authRoute < companyRoute && companyRoute < catchAll)
  const localServer = await readFile(new URL('./console/server.mjs', import.meta.url), 'utf8')
  assert.match(localServer, /import \{ handleAgentCompanyAuth \} from '\.\.\/api\/agent-company-auth\.mjs'/)
  assert.match(localServer, /import \{ handleAgentCompany \} from '\.\.\/api\/agent-company\.mjs'/)
  assert.match(localServer, /url\.pathname === '\/api\/agent-company-auth'\s*\? await handleAgentCompanyAuth\(request\)/)
  assert.match(localServer, /url\.pathname === '\/api\/agent-company'\s*\? await handleAgentCompany\(request\)/)
  assert.match(localServer, /if \(result\.cookie\) responseHeaders\['set-cookie'\] = result\.cookie/)
  assert.match(localServer, /requested === '\/status'/)
  assert.match(localServer, /target\.startsWith\(`\$\{publicRoot\}\$\{sep\}`\)/)
  assert.match(localServer, /CONTENT_TYPES\[extname\(target\)\]/)
})

test('console inline scripts parse after Agent Company wiring', async () => {
  const html = await readConsole()
  const scripts = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map((match) => match[1])
  assert.ok(scripts.length)
  for (const source of scripts) assert.doesNotThrow(() => new Function(source))
})
