import { readFile } from 'node:fs/promises'
import { test } from 'node:test'
import assert from 'node:assert/strict'

test('console exposes the configured workcell activation flow with mobile-safe controls', async () => {
  const html = await readFile(new URL('./public/index.html', import.meta.url), 'utf8')
  assert.match(html, /data-view="workcells"/)
  assert.match(html, /id="view-workcells"/)
  assert.match(html, /api\('GET','\/api\/workcells'\)/)
  assert.match(html, /api\('POST','\/api\/workcells',\{slug,deliver,queueAction\}\)/)
  assert.match(html, /data-queue type="checkbox"/)
  assert.match(html, /w\.configured\?'configured':'needs setup'/)
  assert.doesNotMatch(html, /w\.ready\?'ready'/)
  assert.match(html, /\.workcell \.wc-actions button\{min-height:44px\}/)
  assert.match(html, /\.brand\{grid-column:1\/-1;white-space:nowrap\}/)
})

test('console exposes an owner approval inbox with separate review and execution gates', async () => {
  const html = await readFile(new URL('./public/index.html', import.meta.url), 'utf8')
  assert.match(html, /data-view="approvals"/)
  assert.match(html, /id="view-approvals"/)
  assert.match(html, /api\('GET','\/api\/approvals'\)/)
  assert.match(html, /api\('POST','\/api\/approvals',body\)/)
  assert.match(html, /I reviewed this exact task/)
  assert.match(html, /Execute this reviewed task/)
  assert.match(html, /Payload fingerprint:/)
  assert.match(html, /\.approval-actions button\{min-height:44px\}/)
  assert.doesNotMatch(html, /setInterval\(loadApprovals/)
})

test('console exposes a reviewed LINE/Viber evidence inbox with preview and immutable store gates', async () => {
  const html = await readFile(new URL('./public/index.html', import.meta.url), 'utf8')
  assert.match(html, /id="ownerEvidencePanel"/)
  assert.match(html, /id="ownerEvidenceSource"/)
  assert.match(html, /<option value="viber">Viber<\/option><option value="line">LINE<\/option>/)
  assert.match(html, /api\('POST','\/api\/owner-evidence',\{command:'preview'/)
  assert.match(html, /api\('POST','\/api\/owner-evidence',\{/)
  assert.match(html, /command:'store'/)
  assert.match(html, /I reviewed this exact update for this client/)
  assert.match(html, /Payload fingerprint:/)
  assert.match(html, /\.owner-evidence-actions button\{min-height:44px\}/)
  assert.doesNotMatch(html, /ownerEvidenceDraft\.items\.map\(item=>\(\{\.\.\.item/)
})

test('console builds a canonical client activation plan without collecting credentials', async () => {
  const html = await readFile(new URL('./public/index.html', import.meta.url), 'utf8')
  assert.match(html, /id="activationOpen"/)
  assert.match(html, /id="activationForm"/)
  assert.match(html, /api\('POST','\/api\/workcell-plan',\{scope:\$\('#activationScope'\)\.value\.trim\(\),manifest\}\)/)
  assert.match(html, /id="activationDownloadManifest"/)
  assert.match(html, /src="\/workcell-manifest-import\.js"/)
  assert.match(html, /id="activationManifestFile" type="file" accept="\.json,application\/json"/)
  assert.match(html, /id="activationImportManifest"/)
  assert.match(html, /SuperMegaManifestImport\.parseActivationManifest\(await file\.text\(\)\)/)
  assert.match(html, /Manifest imported\. Add the client-owned ClickUp List ID\./)
  assert.match(html, /selected==='pipeline-control'/)
  assert.match(html, /ClickUp List ID \(optional action queue\)/)
  assert.match(html, /id="activationTokenCap" type="number" min="10000" max="5000000"/)
  assert.match(html, /tokenCap:Number\(\$\('#activationTokenCap'\)\.value\)/)
  assert.match(html, /if\(location\.hash==='\#activation'\)/)
  assert.match(html, /Enter the owner key to load live workcell status\./)
  assert.match(html, /if\(activeView==='workcells'\)/)
  assert.match(html, /activationPlan\.requiredSecretInputs/)
  assert.match(html, /id="activationGuidedCommand"/)
  assert.match(html, /id="activationCopyGuided"/)
  assert.match(html, /npm run workcell:activate -- --manifest/)
  assert.match(html, /copyActivationText\(activationGuidedCommand,'Guided command copied'\)/)
  assert.match(html, /\.activation-fields input,\.activation-fields select\{min-height:44px\}/)
  assert.match(html, /@media\(max-width:520px\)/)
  const panel = html.match(/<div class="activation" id="activationPanel"[\s\S]*?<div id="workcellGrid"/)?.[0] || ''
  assert.ok(panel)
  assert.doesNotMatch(panel, /type="password"|name="[^"]*(?:secret|token|key)/i)
  const importFunction = html.match(/async function importActivationManifestFile\(\)\{[\s\S]*?\n\}/)?.[0] || ''
  assert.ok(importFunction)
  assert.doesNotMatch(importFunction, /\bapi\s*\(|fetch\s*\(/)
})

test('Vercel serves the guarded workcell function before the generic API route', async () => {
  const config = JSON.parse(await readFile(new URL('./vercel.json', import.meta.url), 'utf8'))
  assert.equal(config.functions['api/workcells.mjs'].maxDuration, 45)
  assert.equal(config.functions['api/workcell-plan.mjs'].maxDuration, 10)
  assert.equal(config.functions['api/owner-evidence.mjs'].maxDuration, 15)
  assert.equal(config.functions['api/approvals.mjs'].maxDuration, 30)
  const planRoute = config.routes.findIndex((route) => route.src === '/api/workcell-plan')
  const workcellRoute = config.routes.findIndex((route) => route.src === '/api/workcells')
  const evidenceRoute = config.routes.findIndex((route) => route.src === '/api/owner-evidence')
  const approvalRoute = config.routes.findIndex((route) => route.src === '/api/approvals')
  const catchAll = config.routes.findIndex((route) => route.src === '/api/(.*)')
  assert.ok(planRoute >= 0 && planRoute < catchAll)
  assert.ok(workcellRoute >= 0 && workcellRoute < catchAll)
  assert.ok(evidenceRoute >= 0 && evidenceRoute < catchAll)
  assert.ok(approvalRoute >= 0 && approvalRoute < catchAll)
  assert.deepEqual(config.crons, [{ path: '/api/brief', schedule: '30 1 * * *' }])
})

test('Vercel upload excludes test suites and browser QA artifacts', async () => {
  const ignore = await readFile(new URL('./.vercelignore', import.meta.url), 'utf8')
  assert.match(ignore, /^\*\*\/\*\.test\.mjs$/m)
  assert.match(ignore, /^\.playwright-cli\/$/m)
  assert.match(ignore, /^output\/$/m)
})
