export type AgentInfrastructureRelease = {
  id: string
  provider: 'OpenAI' | 'Google Cloud' | 'Vercel' | 'Anthropic' | 'Protocol'
  name: string
  status: 'Adopt now' | 'Prototype' | 'Watch'
  productMove: string
  platformImpact: string
  modules: string[]
  implementation: string[]
  sourceLabel: string
  sourceUrl: string
}

export type AgentInfrastructureDecision = {
  id: string
  decision: string
  why: string
  nextBuild: string
}

export const AGENT_INFRASTRUCTURE_RADAR: AgentInfrastructureRelease[] = [
  {
    id: 'langgraph-durable-agent-workflows',
    provider: 'Protocol',
    name: 'LangGraph durable workflow core',
    status: 'Adopt now',
    productMove: 'Use LangGraph-style durable graphs for connector jobs, CAPA chains, source-change review, and any agent process that must pause, retry, or wait for approval.',
    platformImpact: 'This keeps the portal from becoming a chat transcript. Long-running work becomes checkpoints, review nodes, idempotent tool calls, and auditable state.',
    modules: ['Agent Workbench', 'Connector Ops', 'Industrial OS', 'Portal Factory'],
    implementation: [
      'Model each high-risk workflow as Capture, Plan, Run, Verify, Learn nodes with a run id and tenant scope.',
      'Use checkpoints and human review gates for connector retries, CAPA packets, and rollout provisioning.',
      'Promote only the durable workflow contract into production when the framework is still in prototype.',
    ],
    sourceLabel: 'LangGraph durable execution',
    sourceUrl: 'https://docs.langchain.com/oss/python/langgraph/durable-execution',
  },
  {
    id: 'anthropic-financial-services-managed-agents',
    provider: 'Anthropic',
    name: 'Claude plugin and managed-agent cookbook pattern',
    status: 'Adopt now',
    productMove: 'Turn every client portal into a skill pack with reader, orchestrator, critic, and resolver agents instead of an unbounded assistant.',
    platformImpact: 'This gives SuperMega a cleaner enterprise story: explicit skills, manifests, tool permissions, callable subagents, and schema-like handoff discipline.',
    modules: ['Agent Workbench', 'Client Build', 'Portal Factory', 'Security'],
    implementation: [
      'Add a reusable agent skill library that emits portal-specific teams, commands, connectors, review gates, and staged outputs.',
      'Use Claude/Anthropic as a second-model critic lane once Claude Code and ANTHROPIC_API_KEY are configured.',
      'Require reader-only handling for untrusted customer files and independent critic checks before resolver output is promoted.',
    ],
    sourceLabel: 'Anthropic financial-services reference repo',
    sourceUrl: 'https://github.com/anthropics/financial-services',
  },
  {
    id: 'openai-agents-sandbox-harness',
    provider: 'OpenAI',
    name: 'Agents SDK sandbox harness',
    status: 'Adopt now',
    productMove: 'Turn R&D, data cleanup, and client portal setup into controlled workspace jobs with files, shell tools, patch output, and review gates.',
    platformImpact: 'This becomes the default execution pattern for SuperMega work cells: workspace in, evidence out, human approval before production writeback.',
    modules: ['Agent Runtime', 'R&D Lab', 'Data Science Studio', 'Build Studio'],
    implementation: [
      'Represent every agent run as a workspace manifest with mounted inputs and named output folders.',
      'Keep credentials outside the sandbox and pass only scoped files, URLs, and temporary tokens.',
      'Store final artifacts, patch summaries, and evidence rows in the tenant ledger.',
    ],
    sourceLabel: 'OpenAI Agents SDK docs',
    sourceUrl: 'https://openai.github.io/openai-agents-python/',
  },
  {
    id: 'mastra-crewai-pydantic-rd-bench',
    provider: 'Protocol',
    name: 'Mastra, CrewAI, and Pydantic AI bench',
    status: 'Prototype',
    productMove: 'Compare modern agent frameworks in the R&D lane, then ship only the validated module contract through SuperMega roles, gates, and ledgers.',
    platformImpact: 'This keeps creativity high without turning production into a framework zoo. R&D can test crews, typed agents, workflows, and critics while production remains simple.',
    modules: ['R&D Lab', 'Agent Workbench', 'Prototype Forge', 'Portal Factory'],
    implementation: [
      'Create one benchmark task per framework: menu extraction, CAPA draft, source-change summary, and module readiness review.',
      'Score each bench on setup speed, tool policy, trace quality, state durability, and ability to export a production contract.',
      'Keep live client credentials out of R&D benches until the security gate and audit ledger are satisfied.',
    ],
    sourceLabel: 'Mastra docs',
    sourceUrl: 'https://mastra.ai/docs',
  },
  {
    id: 'google-agent-engine-governance',
    provider: 'Google Cloud',
    name: 'Vertex AI Agent Engine lane',
    status: 'Prototype',
    productMove: 'Use Google Cloud as the enterprise-grade comparison lane for managed agent runtime, sessions, memory, evaluation, identity, and observability.',
    platformImpact: 'For Drive-heavy clients like Factory Client, this gives us a path to governed Google Workspace agents without rewriting the core portal.',
    modules: ['Connector Ops', 'Knowledge Graph', 'Tenant Control Plane', 'YTF Data Manager'],
    implementation: [
      'Prototype one ADK/Agent Engine worker for Drive change classification and daily owner brief.',
      'Map our tenant session, memory, and run evidence contracts to Agent Engine concepts.',
      'Evaluate VPC-SC, IAM agent identity, logs, and trace posture before client production use.',
    ],
    sourceLabel: 'Google ADK overview',
    sourceUrl: 'https://docs.cloud.google.com/vertex-ai/generative-ai/docs/agent-development-kit/overview',
  },
  {
    id: 'gemini-enterprise-agent-registry',
    provider: 'Google Cloud',
    name: 'Gemini Enterprise agent registry',
    status: 'Watch',
    productMove: 'Use the Gemini Enterprise pattern as the benchmark for how buyers expect to discover, govern, and approve company agents.',
    platformImpact: 'Our Meta workspace should show a clear internal agent gallery with owner, permissions, tools, data scope, and approval policy.',
    modules: ['Meta Workspace', 'Security', 'Agent Teams', 'Client Portal'],
    implementation: [
      'Add an agent registry card for every SuperMega work cell.',
      'Show tool access, write scope, risk level, and last reviewed evidence in one row.',
      'Keep A2A/MCP compatibility as a product requirement, not an optional integration.',
    ],
    sourceLabel: 'Gemini Enterprise agents',
    sourceUrl: 'https://cloud.google.com/gemini-enterprise/agents',
  },
  {
    id: 'vercel-sandbox-ai-gateway',
    provider: 'Vercel',
    name: 'Vercel Sandbox + AI Gateway',
    status: 'Adopt now',
    productMove: 'Route deployed portal agents through one model gateway and run risky file/data analysis inside disposable compute.',
    platformImpact: 'This supports product proof routes, production observability, fallback models, and sandboxed analysis without building a custom infra layer first.',
    modules: ['Cloud Ops', 'Agent Runtime', 'Data Science Studio', 'Production Readiness'],
    implementation: [
      'Use AI Gateway for provider routing, spend visibility, and fallback policy.',
      'Use Vercel Sandbox for isolated file analysis jobs once credentials and billing are configured.',
      'Attach gateway/sandbox status to production readiness so product claims stay honest.',
    ],
    sourceLabel: 'Vercel agents guide',
    sourceUrl: 'https://vercel.com/docs/agents',
  },
  {
    id: 'cloudflare-durable-agent-actors',
    provider: 'Protocol',
    name: 'Durable long-running agent actors',
    status: 'Prototype',
    productMove: 'Use stateful agent actors for source-change watchers, client workrooms, and background jobs that wake on events instead of staying always-on.',
    platformImpact: 'This is the clean path for scalable agent workforces once the current Vercel app and Postgres ledger are stable.',
    modules: ['Agent Runtime', 'Connector Ops', 'Data Fabric', 'Client Portal'],
    implementation: [
      'Prototype one source-change watcher that persists state, schedules follow-up, and writes back to the SuperMega ledger.',
      'Keep the actor identity tied to tenant, module, and source scope.',
      'Use the current Meta Ops route as the operator console before deploying any always-on agent lane.',
    ],
    sourceLabel: 'Cloudflare long-running agents',
    sourceUrl: 'https://developers.cloudflare.com/agents/concepts/long-running-agents/',
  },
  {
    id: 'browser-use-workflow-capture',
    provider: 'Protocol',
    name: 'Browser workflow capture lane',
    status: 'Prototype',
    productMove: 'Use cloud browser agents to turn repeated SaaS and website work into screenshots, extracted fields, risk points, and module specs.',
    platformImpact: 'This is how SuperMega replaces manual browser work without pretending every click should be autonomous on day one.',
    modules: ['Agent Workbench', 'Workforce Command', 'Prototype Forge', 'Connector Ops'],
    implementation: [
      'Create browser run manifests with URL allowlist, stop points, screenshot outputs, and no credential capture.',
      'Use Browser Use for cloud browser tasks and Playwright for deterministic smoke checks.',
      'Promote only workflows with visible approval gates into app modules.',
    ],
    sourceLabel: 'Browser Use quick start',
    sourceUrl: 'https://docs.browser-use.com/introduction',
  },
  {
    id: 'openclaw-local-operator-lab',
    provider: 'Protocol',
    name: 'OpenClaw local operator lab',
    status: 'Prototype',
    productMove: 'Use OpenClaw as an R&D reference for local, persistent operator assistants that can observe folders, browser steps, and desktop workflows before we convert them into SuperMega modules.',
    platformImpact: 'This gives us a credible path for client-side workflow capture without pretending a cloud agent should have unrestricted access to a client computer or private files.',
    modules: ['R&D Lab', 'Open Source Radar', 'Agent Workbench', 'Client Build'],
    implementation: [
      'Keep OpenClaw-style workers in dev/R&D mode with no production tenant secrets and no customer writeback.',
      'Require a local run manifest with allowed folders, allowed URLs/apps, redaction policy, output folder, and human review owner.',
      'Promote only the captured workflow packet into Portal Factory after the operator approves source scope and privacy flags.',
    ],
    sourceLabel: 'OpenClaw GitHub repository',
    sourceUrl: 'https://github.com/openclaw/openclaw',
  },
  {
    id: 'openhands-code-agent-bench',
    provider: 'Protocol',
    name: 'OpenHands coding-agent bench',
    status: 'Prototype',
    productMove: 'Benchmark open-source software-development agents against Codex-style workcells for isolated module builds, patch proposals, QA loops, and repo hygiene tasks.',
    platformImpact: 'This keeps SuperMega agentic development practical: compare real patches and tests, then ship through our own release gate instead of exposing raw framework behavior to clients.',
    modules: ['Agent Workbench', 'Build Studio', 'Prototype Forge', 'Security'],
    implementation: [
      'Run one isolated repo task with dummy data and no production secrets.',
      'Score patch quality, test coverage, tool safety, trace clarity, and ability to produce a bounded implementation proposal.',
      'Use the result to strengthen the native SuperMega builder workcell rather than replacing it blindly.',
    ],
    sourceLabel: 'OpenHands GitHub repository',
    sourceUrl: 'https://github.com/OpenHands/OpenHands',
  },
  {
    id: 'composio-tool-broker-bench',
    provider: 'Protocol',
    name: 'Agent tool broker comparison',
    status: 'Prototype',
    productMove: 'Use Composio and MCP-style patterns as a comparison lane for SaaS tool auth, connector scopes, and action logging.',
    platformImpact: 'The product moat becomes the governed tool plane: every agent action is tied to tenant, role, source, OAuth scope, approval gate, and audit evidence.',
    modules: ['Meta Tools', 'Connector Ops', 'Agent Teams', 'Security'],
    implementation: [
      'Classify every tool as perceive, reason, or act before an agent can use it.',
      'Show OAuth scope, risk tier, last run, approval owner, timeout, and rollback note in Meta Tools.',
      'Keep action tools in dry-run until tool-broker critic checks pass.',
    ],
    sourceLabel: 'Composio GitHub repository',
    sourceUrl: 'https://github.com/ComposioHQ/composio',
  },
  {
    id: 'agent-protocol-plane',
    provider: 'Protocol',
    name: 'MCP, A2A, AGENTS.md, skills',
    status: 'Adopt now',
    productMove: 'Standardize how agents learn the workspace, discover tools, call connectors, and exchange work with other agents.',
    platformImpact: 'This prevents one-off automation scripts from becoming the platform. Every module gets the same tool contract and audit trail.',
    modules: ['Tool Plane', 'Connector Ops', 'Agent Teams', 'Security'],
    implementation: [
      'Treat AGENTS.md as the runtime constitution for each repo and tenant workspace.',
      'Expose approved connectors through MCP-style tool definitions with role-based policy.',
      'Use skills/templates for repeatable module builds, not ad hoc prompt memory.',
    ],
    sourceLabel: 'OpenAI Agents SDK primitives',
    sourceUrl: 'https://openai.com/index/the-next-evolution-of-the-agents-sdk/',
  },
  {
    id: 'autogen-multi-agent-bench',
    provider: 'Protocol',
    name: 'AutoGen multi-agent bench',
    status: 'Prototype',
    productMove: 'Use AutoGen as a comparison lane for multi-agent conversations, distributed runtimes, Docker execution, and MCP workbench support.',
    platformImpact: 'This keeps SuperMega current with enterprise agent-team patterns while production remains governed by our own role, tool, and approval contracts.',
    modules: ['R&D Lab', 'Agent Teams', 'Security', 'Model Ops'],
    implementation: [
      'Run the same module-build task through AutoGen, CrewAI, and native SuperMega workcells.',
      'Score each bench on setup speed, trace quality, tool policy, checkpointing, and ability to export a production module contract.',
      'Do not connect live tenant credentials to any R&D framework until tool broker rules pass.',
    ],
    sourceLabel: 'AutoGen docs',
    sourceUrl: 'https://microsoft.github.io/autogen/stable/',
  },
  {
    id: 'recursive-mas-workcells',
    provider: 'Protocol',
    name: 'Recursive multi-agent workcells',
    status: 'Prototype',
    productMove: 'Use recursive planner, worker, critic, verifier, and human-approval loops for complex industrial packets instead of single-shot agent output.',
    platformImpact: 'This gives SuperMega a disciplined way to make agents creative without turning the portal into an uncontrolled swarm.',
    modules: ['R&D Lab', 'Agent Runtime', 'Industrial OS', 'Portal Factory'],
    implementation: [
      'Add a recursive workcell manifest with roles, iteration cap, source scope, output schema, and review gate.',
      'Use the pattern first for CAPA packet drafting, supplier claims, CEO briefs, and module readiness checks.',
      'Record each recursive round in the evidence ledger before any output is promoted.',
    ],
    sourceLabel: 'RecursiveMAS paper',
    sourceUrl: 'https://huggingface.co/papers/2604.25917',
  },
  {
    id: 'agent-security-gym',
    provider: 'Protocol',
    name: 'Agent security gym',
    status: 'Adopt now',
    productMove: 'Turn agent safety into repeatable drills for goal hijack, unsafe tool use, poisoned memory, and insecure delegation.',
    platformImpact: 'Autonomous agents become easier to sell because risks are tested, visible, and tied to release gates.',
    modules: ['Security', 'Meta Ops', 'Agent Teams', 'Connector Ops'],
    implementation: [
      'Add red-team drills to release gates for every agent with writeback or external tool access.',
      'Block promotion when a module cannot preserve task goal, source scope, tool allowlist, and approval gate.',
      'Store drill results next to QA runs and agent evidence.',
    ],
    sourceLabel: 'GitHub Secure Code Game for AI agents',
    sourceUrl: 'https://github.blog/security/hack-the-ai-agent-build-agentic-ai-security-skills-with-the-github-secure-code-game/',
  },
  {
    id: 'hf-open-agent-bench',
    provider: 'Protocol',
    name: 'Hugging Face open-agent bench',
    status: 'Prototype',
    productMove: 'Use smolagents and open-model tools as a sandbox bench for menu extraction, data cleanup, and model/tool comparisons.',
    platformImpact: 'R&D can move faster while production still runs through SuperMega auth, evidence, and review contracts.',
    modules: ['R&D Lab', 'Data Science Studio', 'Restaurant POS + Inventory', 'Connector Ops'],
    implementation: [
      'Keep open-source agent experiments in isolated R&D tasks.',
      'Promote only the workflow contract, eval, and UI result into production modules.',
      'Compare local/open models for cost-sensitive extraction workloads before committing to hosted inference.',
    ],
    sourceLabel: 'Hugging Face smolagents',
    sourceUrl: 'https://huggingface.co/docs/smolagents/index',
  },
  {
    id: 'github-cli-release-plane',
    provider: 'Protocol',
    name: 'GitHub CLI release lane',
    status: 'Adopt now',
    productMove: 'Give build agents a controlled path to inspect repo health, CI runs, PRs, releases, and deployment blockers without embedding credentials in remotes.',
    platformImpact: 'Meta Ops can now show whether release-agent tooling is installed, authenticated, and safe before any automation touches GitHub or Vercel.',
    modules: ['Meta Ops', 'Build Studio', 'Product Ops', 'Agent Teams'],
    implementation: [
      'Expose gh installation, auth, branch, dirty tree, and remote credential hygiene in Meta Ops.',
      'Keep token material in the GitHub CLI credential store or Vercel/GitHub integrations, never in git remotes.',
      'Use tagged QA runs and release evidence before deploy aliases are moved.',
    ],
    sourceLabel: 'GitHub CLI manual',
    sourceUrl: 'https://cli.github.com/manual/',
  },
]

export const AGENT_INFRASTRUCTURE_DECISIONS: AgentInfrastructureDecision[] = [
  {
    id: 'one-default-lane',
    decision: 'Default lane: OpenAI Agents SDK for coded SuperMega work cells, with recursive patterns only for high-value work.',
    why: 'It matches our current build style: files, terminal checks, patch output, evidence, human review, and now planner/critic/verifier loops when justified.',
    nextBuild: 'Create the first recursive workcell manifest for CAPA packets, supplier claims, CEO briefs, and portal manifests.',
  },
  {
    id: 'one-enterprise-lane',
    decision: 'Enterprise comparison lane: Google Agent Engine for Google Workspace-heavy clients.',
    why: 'It provides managed runtime, sessions, memory, IAM, VPC controls, evaluation, logging, and A2A positioning.',
    nextBuild: 'Build a Drive-change watcher worker spec for Factory Client and map it to our portal ledger.',
  },
  {
    id: 'one-cloud-lane',
    decision: 'Cloud deployment lane: Vercel AI Gateway plus sandboxed jobs.',
    why: 'The product already runs on Vercel, so model routing, spend control, and deployed agent APIs should live near the app.',
    nextBuild: 'Add AI gateway and sandbox readiness checks behind explicit env flags.',
  },
  {
    id: 'one-security-lane',
    decision: 'Security lane: no autonomous writeback without agentic red-team drills.',
    why: 'GitHub and OWASP-style agent security risks are now product risks, not abstract model risks.',
    nextBuild: 'Record goal-hijack, tool-misuse, memory-poisoning, and inter-agent-trust drills in Meta Ops QA evidence.',
  },
  {
    id: 'one-local-lab-lane',
    decision: 'Local lab lane: OpenClaw/OpenHands are R&D accelerators, not production authority.',
    why: 'They help us learn desktop, browser, and code-agent workflows quickly, but production still needs SuperMega tenant scope, evidence, approval, and release gates.',
    nextBuild: 'Add local run manifests for allowed folders, allowed apps/URLs, redaction policy, output artifact, and review owner before any local assistant captures client workflow evidence.',
  },
]
