export type PlatformLayerId = 'foundation' | 'knowledge' | 'automation' | 'workflow' | 'intelligence'

export type PlatformLayer = {
  id: PlatformLayerId
  name: string
  summary: string
  replaces: string[]
  outcome: string
}

export type PlatformCapability = {
  id: string
  layerId: PlatformLayerId
  name: string
  strap: string
  purpose: string
  users: string
  agentRole: string
  replaces: string[]
  route?: string
}

export const PLATFORM_LAYERS: PlatformLayer[] = [
  {
    id: 'foundation',
    name: 'Foundation',
    summary: 'The shared runtime, identity, tenancy, and connectors that make the platform feel like one system instead of a pile of tools.',
    replaces: ['standalone admin tools', 'manual user provisioning', 'ad hoc API glue'],
    outcome: 'One secure operating base for staff, clients, partners, and agents.',
  },
  {
    id: 'knowledge',
    name: 'Knowledge',
    summary: 'The company memory layer that stores decisions, documents, playbooks, client context, and operational history.',
    replaces: ['scattered docs', 'lost chat context', 'orphaned files and notes'],
    outcome: 'A reusable knowledge system every workflow and agent can read from.',
  },
  {
    id: 'automation',
    name: 'Automation',
    summary: 'The orchestration layer for intake, routing, reminders, approvals, and proactive escalation.',
    replaces: ['patchwork automations', 'manual follow-up', 'invisible workflow debt'],
    outcome: 'Agents handle repetitive preparation work before people open the system.',
  },
  {
    id: 'workflow',
    name: 'Workflows',
    summary: 'The daily operating modules people actually live in: sales, ops, portal, support, commerce, and specialist queues.',
    replaces: ['fragmented SaaS categories', 'spreadsheet operations', 'chat-driven execution'],
    outcome: 'One modular software surface for real company work.',
  },
  {
    id: 'intelligence',
    name: 'Intelligence',
    summary: 'Leadership and analytics surfaces built from live workflows and memory, not from disconnected reporting projects.',
    replaces: ['stale dashboards', 'manual status recaps', 'retroactive reporting only'],
    outcome: 'Shorter decision cycles with clearer operational knowledge.',
  },
]

export const PLATFORM_CAPABILITIES: PlatformCapability[] = [
  {
    id: 'tenant-portal-builder',
    layerId: 'foundation',
    name: 'Tenant and Portal Builder',
    strap: 'Branded workspaces for each company, team, client, supplier, or partner.',
    purpose: 'Publish role-specific portals from the same shared base without rebuilding access and layout rules each time.',
    users: 'Operators, admins, client success, implementation teams',
    agentRole: 'Agents can provision default views, handoff states, and portal scaffolding from templates.',
    replaces: ['custom admin consoles', 'manual portal setup'],
    route: '/platform',
  },
  {
    id: 'identity-access',
    layerId: 'foundation',
    name: 'Identity and Access Graph',
    strap: 'One role model for staff, managers, clients, vendors, and external partners.',
    purpose: 'Control which queues, files, approvals, and portal views each user can see or act on.',
    users: 'Operations leads, security owners, admins',
    agentRole: 'Agents apply the right visibility, escalation audience, and approval participants by role.',
    replaces: ['permission spreadsheets', 'manual access fixes'],
    route: '/platform',
  },
  {
    id: 'connector-mesh',
    layerId: 'foundation',
    name: 'Connector Mesh',
    strap: 'Inbox, drive, sheets, ERP extracts, forms, and export feeds into one shared event layer.',
    purpose: 'Bring existing business inputs into the platform without waiting for a full rip-and-replace integration project.',
    users: 'Implementation teams, operators, data admins',
    agentRole: 'Agents watch incoming data, classify it, and attach it to the right account, queue, or decision context.',
    replaces: ['manual imports', 'one-off scripts', 'copy-paste syncing'],
    route: '/platform',
  },
  {
    id: 'agent-runtime',
    layerId: 'foundation',
    name: 'Agent Runtime',
    strap: 'Event-driven agents for intake, summaries, routing, monitoring, and follow-up.',
    purpose: 'Give every module a native agent layer instead of bolting automation on afterward.',
    users: 'Operators, managers, founders',
    agentRole: 'Runs workflow-specific agents with role rules, escalation boundaries, and memory access.',
    replaces: ['standalone copilots', 'manual triage work'],
    route: '/platform',
  },
  {
    id: 'company-memory',
    layerId: 'knowledge',
    name: 'Company Memory',
    strap: 'A durable record of accounts, projects, vendors, requests, files, deadlines, and decisions.',
    purpose: 'Keep context in one place so every system and every agent works from the same company reality.',
    users: 'Everyone in the company',
    agentRole: 'Agents read and update shared company memory instead of generating disposable context each time.',
    replaces: ['lost history', 'searching five tools for context'],
    route: '/platform',
  },
  {
    id: 'decision-journal',
    layerId: 'knowledge',
    name: 'Decision Journal',
    strap: 'Every approval, exception, policy choice, and commitment attached to the source record.',
    purpose: 'Make operational decisions queryable later by account, supplier, project, site, or manager.',
    users: 'Managers, founders, finance, ops',
    agentRole: 'Agents summarize decision history before new approvals and flag repeated exception patterns.',
    replaces: ['approval screenshots', 'buried email decisions'],
    route: '/contact?package=Decision%20Journal',
  },
  {
    id: 'document-intelligence',
    layerId: 'knowledge',
    name: 'Document Intelligence',
    strap: 'Classify, extract, route, and attach files to the right workflow automatically.',
    purpose: 'Turn incoming documents into visible work instead of leaving them in folders and inboxes.',
    users: 'Finance, procurement, warehouse, admin, delivery teams',
    agentRole: 'Agents extract fields, suggest owners, and open the next step automatically.',
    replaces: ['manual file sorting', 'document inboxes with no workflow'],
    route: '/contact?package=Document%20Intelligence',
  },
  {
    id: 'knowledge-hub',
    layerId: 'knowledge',
    name: 'Knowledge Hub',
    strap: 'SOPs, onboarding paths, playbooks, and operational learning in one structured system.',
    purpose: 'Make institutional knowledge part of the operating software instead of a dead wiki.',
    users: 'Internal teams, partners, onboarding leads',
    agentRole: 'Agents suggest the right SOPs, training, or context when work enters a queue.',
    replaces: ['static wikis', 'orphaned onboarding docs'],
    route: '/contact?package=Knowledge%20Hub',
  },
  {
    id: 'intake-router',
    layerId: 'automation',
    name: 'Intake Router',
    strap: 'Convert emails, forms, chats, and uploads into owned records and tasks.',
    purpose: 'Make inbound work immediately visible inside the right operating module.',
    users: 'Ops teams, service teams, sales teams, admins',
    agentRole: 'Agents classify the intake, infer urgency, and assign the first owner.',
    replaces: ['shared inbox triage', 'manual copying into trackers'],
    route: '/contact?package=Intake%20Router',
  },
  {
    id: 'follow-up-orchestrator',
    layerId: 'automation',
    name: 'Follow-up Orchestrator',
    strap: 'Keep next steps, reminders, nudges, and overdue work moving automatically.',
    purpose: 'Reduce revenue loss and operational drift caused by silent missed follow-up.',
    users: 'Sales leads, ops managers, account teams',
    agentRole: 'Agents trigger reminders, escalate drift, and suggest next actions based on current state.',
    replaces: ['manual reminder systems', 'forgotten follow-up'],
    route: '/contact?package=Follow-up%20Orchestrator',
  },
  {
    id: 'approval-policy-engine',
    layerId: 'automation',
    name: 'Approval Policy Engine',
    strap: 'Thresholds, evidence requirements, approver chains, and fallback rules.',
    purpose: 'Standardize approval behavior without forcing teams into rigid legacy workflows.',
    users: 'Managers, procurement, finance, founders',
    agentRole: 'Agents gather evidence, enforce policy gates, and chase delayed sign-off.',
    replaces: ['approval emails', 'chat approvals', 'manual routing logic'],
    route: '/contact?package=Approval%20Policy%20Engine',
  },
  {
    id: 'alert-escalation-engine',
    layerId: 'automation',
    name: 'Alert and Escalation Engine',
    strap: 'Push operational risk, SLA drift, and blocked work to the right person at the right time.',
    purpose: 'Turn passive status tracking into active intervention before service or revenue slips.',
    users: 'Managers, site leads, founders',
    agentRole: 'Agents detect risk conditions and send contextual escalation with the underlying evidence.',
    replaces: ['late escalations', 'reactive management only'],
    route: '/contact?package=Alert%20Engine',
  },
  {
    id: 'sales-system',
    layerId: 'workflow',
    name: 'Sales System',
    strap: 'Prospecting, follow-up, quoting, and handoff in one commercial desk.',
    purpose: 'Give the company one sales operating layer instead of splitting context across CRM, sheets, and inboxes.',
    users: 'Sales teams, founders, coordinators',
    agentRole: 'Agents clean lists, enrich accounts, surface stalled deals, and draft next steps.',
    replaces: ['CRM sprawl', 'sales spreadsheets', 'manual lead tracking'],
    route: '/contact?package=Sales%20System',
  },
  {
    id: 'operations-inbox',
    layerId: 'workflow',
    name: 'Operations Inbox',
    strap: 'Requests, issues, approvals, documents, and exceptions in one live queue.',
    purpose: 'Make operational work visible, owned, and reviewable in real time.',
    users: 'Ops teams, warehouse teams, service teams, admins',
    agentRole: 'Agents route new work, detect blockers, and keep the next owner visible.',
    replaces: ['ticketing fragments', 'chat-driven ops', 'paper logs'],
    route: '/contact?package=Operations%20Inbox',
  },
  {
    id: 'client-portal',
    layerId: 'workflow',
    name: 'Client Portal',
    strap: 'Status, approvals, requests, files, onboarding, and delivery communication in one branded workspace.',
    purpose: 'Replace status-chasing and file chaos with a client-facing system attached to the same company memory.',
    users: 'Clients, account managers, delivery teams, service firms',
    agentRole: 'Agents publish updates, collect requests, and keep external communication synchronized with internal work.',
    replaces: ['client email chains', 'scattered shared drives', 'separate portal tools'],
    route: '/contact?package=Client%20Portal',
  },
  {
    id: 'support-service-desk',
    layerId: 'workflow',
    name: 'Support and Service Desk',
    strap: 'Case ownership, SLA tracking, approvals, and knowledge-guided resolution in one support surface.',
    purpose: 'Let service organizations run support without splitting requests, notes, and approvals across multiple SaaS tools.',
    users: 'Support leads, service ops, account teams',
    agentRole: 'Agents classify tickets, suggest SOPs, and summarize account history before reply.',
    replaces: ['helpdesk sprawl', 'manual escalation chains'],
    route: '/contact?package=Support%20Desk',
  },
  {
    id: 'commerce-back-office',
    layerId: 'workflow',
    name: 'Commerce Back Office',
    strap: 'Orders, branches, settlements, stock pressure, and operational follow-up in one commerce control layer.',
    purpose: 'Run branch or storefront operations from the same shared platform instead of adding another back-office suite.',
    users: 'Ops managers, finance, branch leads, commerce teams',
    agentRole: 'Agents monitor settlement drift, branch anomalies, and inventory pressure.',
    replaces: ['commerce ops spreadsheets', 'separate back-office suites'],
    route: '/contact?package=Commerce%20Back%20Office',
  },
  {
    id: 'supplier-portal',
    layerId: 'workflow',
    name: 'Supplier Portal',
    strap: 'Documents, holds, shortages, approvals, and follow-up shared with vendors in one external workspace.',
    purpose: 'Extend the same portal model outward to suppliers and procurement relationships.',
    users: 'Procurement teams, warehouse teams, suppliers',
    agentRole: 'Agents collect missing supplier evidence, route discrepancies, and monitor resolution lag.',
    replaces: ['supplier email loops', 'document chasing'],
    route: '/contact?package=Supplier%20Portal',
  },
  {
    id: 'founder-brief',
    layerId: 'intelligence',
    name: 'Founder Brief',
    strap: 'A daily operating brief built from live queues, approvals, and exceptions.',
    purpose: 'Give leadership the few things that matter now without another dead dashboard project.',
    users: 'Founders, GMs, directors',
    agentRole: 'Agents summarize top risks, missed follow-up, approval debt, and operational drift.',
    replaces: ['manual status recaps', 'stale dashboards'],
    route: '/contact?package=Founder%20Brief',
  },
  {
    id: 'kpi-watch',
    layerId: 'intelligence',
    name: 'KPI Watch',
    strap: 'Targets, misses, and stale metrics tied directly to owners and thresholds.',
    purpose: 'Keep numbers connected to action, not separated into an analytics silo.',
    users: 'Founders, controllers, managers',
    agentRole: 'Agents detect threshold breaks, stale metrics, and anomalous shifts in operating signals.',
    replaces: ['BI-only reporting', 'manual KPI packs'],
    route: '/contact?package=KPI%20Watch',
  },
  {
    id: 'revenue-risk-radar',
    layerId: 'intelligence',
    name: 'Revenue and Risk Radar',
    strap: 'One view of stalled revenue, operational risk, concentration, and unresolved exceptions.',
    purpose: 'Make commercial and operational knowledge usable for daily intervention.',
    users: 'Founders, commercial leads, ops directors',
    agentRole: 'Agents rank risk by likely impact and attach the records that explain it.',
    replaces: ['manual pipeline reviews', 'separate risk spreadsheets'],
    route: '/contact?package=Revenue%20and%20Risk%20Radar',
  },
  {
    id: 'director-command-center',
    layerId: 'intelligence',
    name: 'Director Command Center',
    strap: 'A multi-company or multi-site leadership surface for shared review across portals.',
    purpose: 'Let operators and leadership manage several entities from one next-gen control plane.',
    users: 'Holding company leaders, directors, regional operators',
    agentRole: 'Agents aggregate site or tenant health and surface the few places where intervention is needed.',
    replaces: ['cross-company reporting packs', 'manual rollups'],
    route: '/contact?package=Director%20Command%20Center',
  },
]

export function getPlatformLayerGroups() {
  return PLATFORM_LAYERS.map((layer) => ({
    ...layer,
    capabilities: PLATFORM_CAPABILITIES.filter((capability) => capability.layerId === layer.id),
  }))
}
