export type PlatformBuildStackItem = {
  id: string
  stage: 'Current base' | 'Immediate next layer' | 'Recommended upgrade'
  name: string
  primaryTool: string
  summary: string
  outcome: string
  bestFor: string
  integratesInto: string[]
  sourceLabel: string
  sourceUrl: string
}

export const PLATFORM_BUILD_STACK: PlatformBuildStackItem[] = [
  {
    id: 'frontend-base',
    stage: 'Current base',
    name: 'Simple product UI',
    primaryTool: 'React + Vite + Vercel',
    summary: 'Keep the buyer site, login, and tenant app fast, route-safe, and easy to demo.',
    outcome: 'Ship one clear product surface instead of another crowded SaaS menu.',
    bestFor: 'Landing pages, tenant portals, module detail pages, and static route deployment.',
    integratesInto: ['Public site', 'Manager System', 'Client Portal'],
    sourceLabel: 'Current repo stack',
    sourceUrl: 'https://supermega.dev',
  },
  {
    id: 'runtime-api',
    stage: 'Current base',
    name: 'Workspace runtime',
    primaryTool: 'Python workspace runtime',
    summary: 'Role-aware sessions, queues, approvals, module APIs, rollout control, and tenant data.',
    outcome: 'Make each module save work into one operating record instead of side files.',
    bestFor: 'Role-aware business workflows, approval gates, data writeback, and tenant-specific portals.',
    integratesInto: ['Operations Inbox', 'Industrial DQMS', 'Tenant Control Plane'],
    sourceLabel: 'Current repo runtime',
    sourceUrl: 'https://app.supermega.dev/app/start/',
  },
  {
    id: 'openai-agents-runtime',
    stage: 'Immediate next layer',
    name: 'Agent work layer',
    primaryTool: 'OpenAI AgentKit + Agents SDK',
    summary: 'Use Agent Builder for workflow design and Agents SDK for coded tool orchestration, handoffs, tracing, and reviewed execution.',
    outcome: 'Move from passive dashboards to versioned AI work cells that can be embedded, traced, and evaluated.',
    bestFor: 'Document intake, briefs, policy checks, writeback suggestions, governed copilots, and agent workflow prototyping.',
    integratesInto: ['Document Intelligence', 'Founder Brief', 'Manager System', 'Agent Runtime'],
    sourceLabel: 'OpenAI AgentKit docs',
    sourceUrl: 'https://developers.openai.com/api/docs/guides/agents',
  },
  {
    id: 'openai-sandbox-runtime',
    stage: 'Immediate next layer',
    name: 'Sandboxed computer work',
    primaryTool: 'OpenAI Shell tool + sandbox agents',
    summary: 'Give agents controlled workspaces for files, commands, services, reports, and long-running artifacts without leaking the whole machine.',
    outcome: 'Build safer autonomous R&D and operations workers that can inspect evidence, run tools, and return durable artifacts.',
    bestFor: 'Code/data tasks, spreadsheet/report generation, terminal-backed checks, and repeatable production-system work.',
    integratesInto: ['R&D Lab', 'Build Studio', 'Data Science Studio', 'Agent Runtime'],
    sourceLabel: 'OpenAI shell tool docs',
    sourceUrl: 'https://developers.openai.com/api/docs/guides/tools-shell',
  },
  {
    id: 'mcp-tool-plane',
    stage: 'Immediate next layer',
    name: 'Tool and connector plane',
    primaryTool: 'MCP + A2A + Composio',
    summary: 'Expose Gmail, Drive, GitHub, files, approved business tools, and inter-agent handoffs through one governed protocol layer.',
    outcome: 'Add connectors without turning every product module into custom integration code.',
    bestFor: 'Connector-backed research, file-grounded answers, tenant memory access, external actions, and multi-agent interoperability.',
    integratesInto: ['Knowledge Hub', 'Knowledge Graph', 'Agent Runtime', 'Tenant Control Plane'],
    sourceLabel: 'MCP specification',
    sourceUrl: 'https://modelcontextprotocol.io/specification/2024-11-05/server',
  },
  {
    id: 'recursive-agent-patterns',
    stage: 'Immediate next layer',
    name: 'Recursive agent workcells',
    primaryTool: 'RecursiveMAS pattern library',
    summary: 'Use planner, worker, critic, verifier, and human approval loops for tasks where collaboration beats a single assistant.',
    outcome: 'Better CAPA packets, supplier claims, executive briefs, and portal manifests without turning the whole app into uncontrolled swarms.',
    bestFor: 'Industrial exception handling, source-change reviews, module readiness checks, and client-specific portal generation.',
    integratesInto: ['Agent Runtime', 'R&D Lab', 'Industrial OS', 'Portal Factory'],
    sourceLabel: 'RecursiveMAS paper',
    sourceUrl: 'https://huggingface.co/papers/2604.25917',
  },
  {
    id: 'agent-security-gym',
    stage: 'Immediate next layer',
    name: 'Agent security gym',
    primaryTool: 'GitHub Secure Code Game + OWASP Agentic Top 10',
    summary: 'Turn agent risks into hands-on tests for goal hijack, unsafe tool use, poisoned memory, and insecure delegation.',
    outcome: 'Autonomy grows only after security drills pass and release evidence is recorded.',
    bestFor: 'Connector writeback, agent teams, recursive workcells, GitHub automation, and client data operations.',
    integratesInto: ['Meta Ops', 'Security', 'Agent Teams', 'Release Guard'],
    sourceLabel: 'GitHub agentic security game',
    sourceUrl: 'https://github.blog/security/hack-the-ai-agent-build-agentic-ai-security-skills-with-the-github-secure-code-game/',
  },
  {
    id: 'github-release-agents',
    stage: 'Immediate next layer',
    name: 'Release agent tools',
    primaryTool: 'GitHub CLI + GitHub Actions + Vercel checks',
    summary: 'Let controlled build agents inspect repo state, workflow runs, pull requests, domain aliases, and release blockers from one operator loop.',
    outcome: 'Turn shipping into a repeatable release cell instead of manual dashboard clicking.',
    bestFor: 'CI triage, release health, PR review loops, deployment promotion, and client go-live evidence.',
    integratesInto: ['Meta Ops', 'Build Studio', 'QA History', 'Cloud Ops'],
    sourceLabel: 'GitHub CLI manual',
    sourceUrl: 'https://cli.github.com/manual/',
  },
  {
    id: 'google-gemini-model-lane',
    stage: 'Recommended upgrade',
    name: 'Gemini multimodal lane',
    primaryTool: 'Gemini 3 + Computer Use',
    summary: 'Use Gemini as a secondary model lane for multimodal reasoning, long-context review, generated UI experiments, and browser/mobile control tests.',
    outcome: 'Improve R&D quality without coupling the whole platform to one provider or one model family.',
    bestFor: 'PDF/video/audio review, browser control experiments, generated UI prototypes, and Google Workspace-heavy tenant workflows.',
    integratesInto: ['R&D Lab', 'Document Intelligence', 'Data Fabric', 'Client Portal'],
    sourceLabel: 'Gemini 3 developer guide',
    sourceUrl: 'https://ai.google.dev/gemini-api/docs/gemini-3',
  },
  {
    id: 'google-agent-platform',
    stage: 'Recommended upgrade',
    name: 'Enterprise agent governance',
    primaryTool: 'Google ADK + Gemini Enterprise Agent Platform',
    summary: 'Use Google ADK and Gemini Enterprise patterns as a reference lane for agent identity, registry, runtime, evaluation, and governance.',
    outcome: 'Copy the right enterprise controls before autonomous agents touch client data or production writeback.',
    bestFor: 'Agent registry, BYO service accounts, managed runtime comparison, eval posture, and Google Cloud tenant deployments.',
    integratesInto: ['Tenant Control Plane', 'Security', 'Agent Runtime', 'Cloud Ops'],
    sourceLabel: 'Gemini Enterprise Agent Platform',
    sourceUrl: 'https://docs.cloud.google.com/gemini-enterprise-agent-platform/scale',
  },
  {
    id: 'agent-workflows',
    stage: 'Recommended upgrade',
    name: 'Durable agent workflows',
    primaryTool: 'LangGraph or Temporal',
    summary: 'Use graph/workflow runtimes for long-running jobs that need persistence, retries, and human review.',
    outcome: 'Approvals, connector sync, and agent jobs survive failures instead of disappearing in chat state.',
    bestFor: 'Approval chains, rollout packs, connector retries, and long-running tenant provisioning.',
    integratesInto: ['Approval Policy Engine', 'Tenant Control Plane', 'Agent Runtime'],
    sourceLabel: 'LangGraph docs',
    sourceUrl: 'https://docs.langchain.com/oss/python/langgraph',
  },
  {
    id: 'edge-agents',
    stage: 'Recommended upgrade',
    name: 'Stateful edge agents',
    primaryTool: 'Cloudflare Agents SDK',
    summary: 'Run tenant agent sessions close to users with state, scheduling, WebSockets, and durable execution.',
    outcome: 'Support responsive portal agents and long-lived workrooms without building custom coordination first.',
    bestFor: 'Portal copilots, tenant agent rooms, browser-to-agent sync, and human-in-the-loop flows.',
    integratesInto: ['Client Portal', 'Agent Runtime', 'Workforce Command'],
    sourceLabel: 'Cloudflare Agents docs',
    sourceUrl: 'https://developers.cloudflare.com/agents/',
  },
  {
    id: 'codesign-studio',
    stage: 'Recommended upgrade',
    name: 'Co-design prototyping',
    primaryTool: 'Open CoDesign',
    summary: 'Use local-first AI design to generate focused landing pages, module screens, and pitch decks.',
    outcome: 'Prototype buyer-ready module screens faster without putting the prototype UI into production blindly.',
    bestFor: 'R&D mockups, module variants, onboarding flows, and client-specific proposal screens.',
    integratesInto: ['R&D Lab', 'Build Studio', 'Products page'],
    sourceLabel: 'Open CoDesign',
    sourceUrl: 'https://opencoworkai.github.io/open-codesign/',
  },
  {
    id: 'workflow-prototyping',
    stage: 'Recommended upgrade',
    name: 'Workflow prototype bench',
    primaryTool: 'smolagents / Dify / n8n / Flowise / Google ADK samples',
    summary: 'Use open-source and visual workflow benches only for sandbox prototypes, connector experiments, and model/tool comparisons.',
    outcome: 'Learn fast, then promote only the useful workflow contract into the governed SuperMega runtime.',
    bestFor: 'Menu extraction, data-cleaning prototypes, internal automations, connector trials, and R&D workflow sketches.',
    integratesInto: ['R&D Lab', 'Agent Runtime', 'Connector Ops'],
    sourceLabel: 'Hugging Face smolagents docs',
    sourceUrl: 'https://huggingface.co/docs/smolagents/index',
  },
  {
    id: 'data-memory',
    stage: 'Recommended upgrade',
    name: 'Company memory layer',
    primaryTool: 'Postgres + pgvector + dbt',
    summary: 'Store tenant records, embeddings, provenance, and metrics in one queryable base.',
    outcome: 'Give every module the same company memory and KPI language.',
    bestFor: 'Knowledge graph, entity search, document retrieval, KPI marts, and tenant memory.',
    integratesInto: ['Knowledge Graph', 'Knowledge Hub', 'Document Intelligence'],
    sourceLabel: 'pgvector project',
    sourceUrl: 'https://github.com/pgvector/pgvector',
  },
]
