export type PortalModuleContract = {
  id: string
  portal: 'industrial' | 'restaurant' | 'service'
  name: string
  route?: string
  role: string
  trigger: string
  job: string
  capture: string[]
  sourceTruth: string[]
  decision: string
  kpi: string
  methods: string[]
  agentMoves: string[]
  reviewGate: string
  standout: string
  maturity: 'Live shell' | 'Sellable module' | 'Next build'
}

export type AiNativeInfrastructurePattern = {
  id: string
  name: string
  productUse: string
  stack: string[]
  control: string
  moduleImpact: string
}

export const INDUSTRIAL_MODULE_CONTRACTS: PortalModuleContract[] = [
  {
    id: 'industrial-plant-manager-home',
    portal: 'industrial',
    name: 'Plant Manager Home',
    route: '/app/plant-manager',
    role: 'Plant manager',
    trigger: 'Start of shift, end of shift, or any major blocker.',
    job: 'Choose the top blocker, assign one owner, and open only the desk that can close it.',
    capture: ['Top blocker', 'Owner', 'Due window', 'Owning desk'],
    sourceTruth: ['Daily Entry', 'Action Board', 'Operations desk', 'Data Fabric'],
    decision: 'What must change before the next shift?',
    kpi: 'Time to owned action',
    methods: ['Daily management review', '5W1H', 'Gemba follow-up'],
    agentMoves: ['Prepare the daily focus', 'Cluster repeat blockers', 'Draft shift handover'],
    reviewGate: 'Human manager approves the owner and next action.',
    standout: 'The manager does not browse a suite. The system gives one operating loop.',
    maturity: 'Sellable module',
  },
  {
    id: 'industrial-dqms-control',
    portal: 'industrial',
    name: 'DQMS and CAPA Control',
    route: '/app/dqms',
    role: 'Quality lead',
    trigger: 'Defect, complaint, release hold, repeat B+R signal, or inspection drift.',
    job: 'Turn quality noise into containment, root cause, CAPA, verification, and release evidence.',
    capture: ['Incident', 'Containment', 'Lot or batch', 'Evidence', 'CAPA owner'],
    sourceTruth: ['QC sheets', 'Photos', 'Complaint email', 'Batch context', 'Approval queue'],
    decision: 'Can this lot move, stay on hold, or require escalation?',
    kpi: 'Repeat defect rate',
    methods: ['NCR', '5W1H', 'Ishikawa', 'CAPA verification', 'Management review'],
    agentMoves: ['Draft root-cause branches', 'Find similar incidents', 'Prepare CAPA packet'],
    reviewGate: 'Quality owner approves containment and CAPA before closeout.',
    standout: 'Quality methods become guided software, not blank notes and scattered files.',
    maturity: 'Sellable module',
  },
  {
    id: 'industrial-receiving-control',
    portal: 'industrial',
    name: 'Receiving and Supplier Control',
    route: '/app/receiving',
    role: 'Stores, receiving, procurement',
    trigger: 'Short quantity, wrong item, COA mismatch, damaged material, or supplier delay.',
    job: 'Stop bad inbound material before it contaminates production, inventory, or accounting.',
    capture: ['Supplier', 'PO or PI', 'GRN or batch', 'Quantity gap', 'Hold decision'],
    sourceTruth: ['Supplier invoice', 'COA', 'Receiving photos', 'Purchase order', 'Inventory record'],
    decision: 'Receive, hold, reject, claim, or escalate production risk.',
    kpi: 'Supplier hold aging',
    methods: ['Supplier quality scorecard', 'Traceability event', 'Exception aging'],
    agentMoves: ['Build discrepancy packet', 'Detect repeat supplier gaps', 'Draft supplier follow-up'],
    reviewGate: 'Procurement or plant manager approves claims and release exceptions.',
    standout: 'The first ERP screen becomes an evidence-backed supplier recovery loop.',
    maturity: 'Sellable module',
  },
  {
    id: 'industrial-maintenance-reliability',
    portal: 'industrial',
    name: 'Maintenance Reliability',
    route: '/app/maintenance',
    role: 'Maintenance lead',
    trigger: 'Breakdown, repeat fault, PM miss, spare shortage, or restart risk.',
    job: 'Connect downtime, cause, repair, spare, preventive action, and verification in one lane.',
    capture: ['Asset', 'Downtime', 'Issue type', 'Likely cause', 'Preventive follow-up'],
    sourceTruth: ['Breakdown log', 'PM checklist', 'Inventory', 'Technician note', 'Approval case'],
    decision: 'Restart, work around, escalate, or change PM priority.',
    kpi: 'Downtime and repeat-failure rate',
    methods: ['MTBF', 'MTTR', '5 Why', 'FMEA-lite', 'PM compliance'],
    agentMoves: ['Cluster repeat faults', 'Suggest missing evidence', 'Prepare PM risk list'],
    reviewGate: 'Maintenance lead confirms cause and preventive action.',
    standout: 'Reliability becomes a learning loop instead of a repair log.',
    maturity: 'Sellable module',
  },
  {
    id: 'industrial-executive-brief',
    portal: 'industrial',
    name: 'Executive Brief',
    route: '/app/daily-brief',
    role: 'CEO or director',
    trigger: 'Daily review, major exception, supplier exposure, shipment risk, or recurring KPI drift.',
    job: 'Show the few risks that deserve executive attention, with source links and decision options.',
    capture: ['Top risk', 'Owner', 'Exposure', 'Decision needed', 'Evidence links'],
    sourceTruth: ['Plant Manager', 'DQMS', 'Maintenance', 'Receiving', 'Sales and approvals'],
    decision: 'Approve, intervene, escalate, or wait.',
    kpi: 'Decision cycle time',
    methods: ['Gap analysis', 'Management review', 'Risk register', 'Decision log'],
    agentMoves: ['Draft brief', 'Explain KPI movement', 'Name missing evidence'],
    reviewGate: 'Director approves business decisions; agents only prepare.',
    standout: 'The executive view is built from live operating records, not reporting theater.',
    maturity: 'Sellable module',
  },
  {
    id: 'industrial-agent-workcells',
    portal: 'industrial',
    name: 'Industrial Agent Workcells',
    route: '/app/plant-os',
    role: 'Plant manager, quality lead, maintenance lead, CEO',
    trigger: 'Any repeat defect, breakdown, supplier gap, shift blocker, or daily management review.',
    job: 'Run bounded LLM jobs that assemble evidence, draft next actions, and route review packets to the right industrial module.',
    capture: ['Workcell', 'Trigger', 'Evidence scope', 'Review owner', 'Output packet'],
    sourceTruth: ['Drive', 'Gmail', 'Sheets', 'ERP exports', 'Agent run ledger'],
    decision: 'Approve the drafted packet, request more evidence, or open the owning module.',
    kpi: 'Human review time saved per exception',
    methods: ['CAPA', '5 Why', 'Ishikawa', 'MTBF/MTTR', 'Supplier claim', 'Daily management review'],
    agentMoves: ['Assemble source evidence', 'Draft root-cause tree', 'Build supplier packet', 'Write executive brief'],
    reviewGate: 'Agents can prepare and route; accountable humans approve containment, claims, maintenance actions, and strategy.',
    standout: 'This is where the portal becomes an industrial AI workforce, not a dashboard.',
    maturity: 'Sellable module',
  },
  {
    id: 'industrial-knowledge-runtime',
    portal: 'industrial',
    name: 'Factory Knowledge Runtime',
    route: '/app/data-fabric',
    role: 'Admin, data owner, implementation team',
    trigger: 'New files, changed folders, new ERP export, spreadsheet drift, or source access change.',
    job: 'Turn messy files, emails, sheets, and SOPs into canonical records that modules and agents can trust.',
    capture: ['Source owner', 'Source type', 'Last change', 'Entity proposal', 'Review status'],
    sourceTruth: ['Drive', 'Gmail', 'Sheets', 'ERP exports', 'Manual uploads'],
    decision: 'Promote, merge, reject, or request human clarification.',
    kpi: 'Trusted record rate',
    methods: ['Data lineage', 'Entity resolution', 'Data quality rules', 'Access review'],
    agentMoves: ['Classify files', 'Extract entities', 'Propose cleanup', 'Detect stale sources'],
    reviewGate: 'Data owner approves canonical merges and sensitive relationships.',
    standout: 'The portal learns from the company instead of becoming another static app.',
    maturity: 'Next build',
  },
]

export const RESTAURANT_MODULE_CONTRACTS: PortalModuleContract[] = [
  {
    id: 'restaurant-shift-control',
    portal: 'restaurant',
    name: 'Shift Control',
    role: 'Store manager',
    trigger: 'Opening, rush, close, staff gap, service blocker, or abnormal daypart.',
    job: 'Run the store from one short shift loop: ready, blocked, recovered, handed over.',
    capture: ['Opening status', 'Rush blockers', 'Staff gaps', 'Close notes'],
    sourceTruth: ['POS daypart data', 'Schedule', 'Manager notes', 'Delivery app signals'],
    decision: 'Fix now, hand over, escalate, or train.',
    kpi: 'Open blocker aging',
    methods: ['Shift handover', 'Service recovery', 'Daily manager review'],
    agentMoves: ['Summarize handover', 'Detect repeat blockers', 'Draft area-manager note'],
    reviewGate: 'Store manager approves handover and escalation.',
    standout: 'Managers get a shift operating system, not another checklist app.',
    maturity: 'Next build',
  },
  {
    id: 'restaurant-prep-stock',
    portal: 'restaurant',
    name: 'Prep, Stock, and Waste',
    role: 'Kitchen lead',
    trigger: 'Stock-out risk, prep variance, waste spike, substitution, or supplier short.',
    job: 'Protect service and margin by linking prep, waste, stock, and supplier recovery.',
    capture: ['Prep count', 'Waste photo', 'Stock-out', 'Substitution', 'Supplier issue'],
    sourceTruth: ['POS mix', 'Invoices', 'Prep sheet', 'Waste log', 'Inventory count'],
    decision: 'Prep more, substitute, claim supplier, or change par.',
    kpi: 'Waste and stock-out exceptions',
    methods: ['Par control', 'Yield variance', 'Waste review', 'Supplier discrepancy'],
    agentMoves: ['Draft reorder', 'Explain waste drift', 'Flag branch variance'],
    reviewGate: 'Kitchen or area lead approves par and supplier actions.',
    standout: 'Food cost, service risk, and supplier issues live in the same loop.',
    maturity: 'Next build',
  },
  {
    id: 'restaurant-guest-recovery',
    portal: 'restaurant',
    name: 'Guest Recovery',
    role: 'Area manager',
    trigger: 'Complaint, refund, bad review, delivery issue, repeat service pattern.',
    job: 'Group guest problems into recovery, training, and operating fixes.',
    capture: ['Guest issue', 'Channel', 'Branch', 'Recovery action', 'Training cue'],
    sourceTruth: ['Reviews', 'Delivery apps', 'Refund logs', 'Manager notes'],
    decision: 'Recover, refund, retrain, or change process.',
    kpi: 'Repeat complaint rate',
    methods: ['Service recovery', 'Complaint clustering', 'Training loop'],
    agentMoves: ['Cluster repeated issues', 'Draft recovery message', 'Suggest training cue'],
    reviewGate: 'Manager approves customer-facing action.',
    standout: 'Customer pain becomes operating memory instead of reputation damage.',
    maturity: 'Next build',
  },
  {
    id: 'restaurant-margin-brief',
    portal: 'restaurant',
    name: 'Margin and Promo Brief',
    role: 'Owner operator',
    trigger: 'Promo launch, menu change, margin drop, delivery fee drift, or branch variance.',
    job: 'Show which decisions improve sales without destroying labor, stock, waste, or service.',
    capture: ['Promo', 'Menu item', 'Branch', 'Margin movement', 'Service pressure'],
    sourceTruth: ['POS', 'Promo calendar', 'Inventory', 'Labor schedule', 'Delivery app data'],
    decision: 'Extend, correct, stop, or redesign the promo.',
    kpi: 'Promo contribution after operating pressure',
    methods: ['Contribution margin', 'Daypart comparison', 'Branch variance'],
    agentMoves: ['Explain lift', 'Flag waste/service strain', 'Draft owner summary'],
    reviewGate: 'Owner approves pricing, promo, and menu decisions.',
    standout: 'The brief measures the whole operating effect, not just top-line sales.',
    maturity: 'Next build',
  },
  {
    id: 'restaurant-pos-payment-control',
    portal: 'restaurant',
    name: 'Payment Proof and Cash-Up Control',
    role: 'Owner operator or cashier lead',
    trigger: 'Customer payment, cash-up mismatch, unpaid order, provider export mismatch, or settlement screenshot review.',
    job: 'Capture provider payment links, slips, customer/order evidence, payment status, and settlement proof without storing bank credentials or card data.',
    capture: ['Order reference', 'Customer/contact', 'Items sold', 'Amount MMK', 'Provider', 'Provider payment link', 'Settlement reference', 'Slip or proof note', 'Payment status'],
    sourceTruth: ['Provider payment URL', 'POS receipt', 'Cash-up sheet', 'Screenshot or slip evidence', 'Bank or provider settlement export'],
    decision: 'Paid, pending, reconcile, or escalate mismatch.',
    kpi: 'Unreconciled payment value',
    methods: ['PCI DSS scope awareness', 'Cash-up reconciliation', 'Exception aging', 'Settlement evidence review', 'Human-in-the-loop payment approval'],
    agentMoves: ['Match payment exports to order refs', 'Flag unpaid or mismatched records', 'Draft cash-up exception note', 'Prepare owner settlement review'],
    reviewGate: 'Owner or cashier lead approves payment status changes and settlement exceptions.',
    standout: 'Payments become an operating control loop with proof, status, owner review, and provider source evidence instead of screenshots lost in chat.',
    maturity: 'Sellable module',
  },
  {
    id: 'restaurant-qr-menu-transition',
    portal: 'restaurant',
    name: 'QR Menu Transition',
    role: 'Owner operator, store manager',
    trigger: 'Paper menu update, PDF/image menu upload, new branch launch, price change, or QR ordering rollout.',
    job: 'Turn messy menus into a structured digital menu, customer QR, printable PDF/menu page, and optional order-request flow.',
    capture: ['Menu source files', 'Menu text', 'Items', 'Prices', 'Ordering mode'],
    sourceTruth: ['PDF menu', 'Menu images', 'Manager text', 'POS item export'],
    decision: 'Publish digital menu only, collect order requests, or route to POS integration.',
    kpi: 'Time from menu change to live QR',
    methods: ['Menu engineering', 'Allergen review', 'Price change control', 'Customer journey design'],
    agentMoves: ['Extract menu items', 'Normalize prices', 'Draft item descriptions', 'Flag missing allergen/availability fields'],
    reviewGate: 'Manager approves menu items and prices before QR publication.',
    standout: 'A restaurant can move from PDF/images to a digital menu system without buying a heavy POS stack first.',
    maturity: 'Sellable module',
  },
]

export const SERVICE_MODULE_CONTRACTS: PortalModuleContract[] = [
  {
    id: 'service-client-crm',
    portal: 'service',
    name: 'Client CRM',
    route: '/app/service-desk',
    role: 'Account manager',
    trigger: 'New lead, client reply, stale follow-up, renewal risk, or relationship issue.',
    job: 'Show every active client, relationship status, open request, promised follow-up, and next owner in one view.',
    capture: ['Client', 'Stage', 'Last contact', 'Next promise', 'Owner'],
    sourceTruth: ['Gmail threads', 'Drive client folder', 'meeting notes', 'forms'],
    decision: 'Follow up, escalate, schedule review, or mark risk for founder attention.',
    kpi: 'Follow-up aging',
    methods: ['Account review', 'relationship health', 'next-best-action queue'],
    agentMoves: ['Summarize client history', 'classify next action', 'draft follow-up'],
    reviewGate: 'Account manager approves client-facing messages before sending.',
    standout: 'Small service teams get a CRM that starts from real email and files, not manual data entry first.',
    maturity: 'Sellable module',
  },
  {
    id: 'service-delivery-queue',
    portal: 'service',
    name: 'Delivery Queue',
    route: '/app/service-desk',
    role: 'Project lead',
    trigger: 'Client request, internal blocker, missing file, delivery update, or overdue action.',
    job: 'Turn scattered client work into one owner, status, proof, blocker, and next action queue.',
    capture: ['Request', 'Client', 'Owner', 'Due date', 'Proof needed'],
    sourceTruth: ['tasks', 'Drive docs', 'client messages', 'project notes'],
    decision: 'Do now, block, request evidence, reassign, or escalate scope.',
    kpi: 'Blocked delivery aging',
    methods: ['Kanban flow', 'SLA review', 'proof-of-work ledger'],
    agentMoves: ['Group scattered tasks', 'draft client status', 'flag missing proof'],
    reviewGate: 'Project lead confirms owner, scope, and client-visible status.',
    standout: 'Delivery work becomes billable proof instead of hidden labor across docs and chats.',
    maturity: 'Sellable module',
  },
  {
    id: 'service-meeting-action-tracker',
    portal: 'service',
    name: 'Meeting Action Tracker',
    route: '/app/actions',
    role: 'Client success manager',
    trigger: 'Calendar meeting, discovery call, review note, transcript, or internal handoff.',
    job: 'Turn meetings into decisions, owners, deadlines, follow-up drafts, and delivery queue items.',
    capture: ['Meeting', 'Decision', 'Action item', 'Owner', 'Due date'],
    sourceTruth: ['Calendar events', 'meeting notes', 'Docs', 'transcripts'],
    decision: 'Approve follow-up, create work item, update client record, or request missing context.',
    kpi: 'Meeting action close rate',
    methods: ['Action register', 'decision log', 'client follow-up protocol'],
    agentMoves: ['Extract decisions', 'create action list', 'draft follow-up email'],
    reviewGate: 'Client success manager approves action extraction and external follow-up.',
    standout: 'Meetings stop evaporating into vague notes; they become managed work.',
    maturity: 'Sellable module',
  },
  {
    id: 'service-proposal-builder',
    portal: 'service',
    name: 'Proposal Builder',
    route: '/app/factory',
    role: 'Founder',
    trigger: 'Discovery completed, scope requested, upsell opportunity, or renewal proposal.',
    job: 'Convert discovery notes, examples, pricing assumptions, risks, and proof into a proposal review packet.',
    capture: ['Scope', 'Client pain', 'Proof assets', 'Risks', 'Pricing note'],
    sourceTruth: ['discovery notes', 'client docs', 'case examples', 'pricing notes'],
    decision: 'Approve scope, ask for missing evidence, price, or pause until risk is resolved.',
    kpi: 'Proposal cycle time',
    methods: ['Discovery synthesis', 'scope control', 'commercial review'],
    agentMoves: ['Draft proposal outline', 'flag missing scope evidence', 'prepare founder review'],
    reviewGate: 'Founder approves pricing, scope, and claims before sending.',
    standout: 'The service business can sell faster without inventing every proposal from scratch.',
    maturity: 'Next build',
  },
  {
    id: 'service-billing-readiness',
    portal: 'service',
    name: 'Billing Readiness',
    route: '/app/approvals',
    role: 'Finance',
    trigger: 'Completed work, approval request, retainer review, unpaid invoice, or scope change.',
    job: 'Show which client work is ready to invoice, missing proof, blocked by approval, or drifting outside scope.',
    capture: ['Client', 'Work completed', 'Proof link', 'Approval state', 'Scope risk'],
    sourceTruth: ['delivery queue', 'approval log', 'Stripe products', 'time/proof notes'],
    decision: 'Invoice, request proof, hold billing, or open a scope-change approval.',
    kpi: 'Unbilled completed work',
    methods: ['Revenue assurance', 'approval control', 'scope creep review'],
    agentMoves: ['Prepare invoice packet', 'name missing evidence', 'flag scope creep'],
    reviewGate: 'Finance or founder approves invoice packets before customer billing.',
    standout: 'Revenue leakage becomes visible before the month-end scramble.',
    maturity: 'Sellable module',
  },
]

export const AI_NATIVE_MODULE_INFRA: AiNativeInfrastructurePattern[] = [
  {
    id: 'agent-runtime',
    name: 'Agent runtime with traces',
    productUse: 'Run bounded jobs for summaries, cleanup, analysis, and drafts.',
    stack: ['OpenAI Agents SDK', 'Responses API tools', 'Vertex AI Agent Engine or ADK'],
    control: 'Every run records input scope, tools, output, confidence, and review status.',
    moduleImpact: 'Turns AI from chat into auditable work inside DQMS, maintenance, receiving, and executive brief modules.',
  },
  {
    id: 'durable-workflows',
    name: 'Durable workflow engine',
    productUse: 'Keep long-running sync, review, retry, and approval jobs alive.',
    stack: ['Vercel Workflow', 'Temporal', 'Cloud Tasks'],
    control: 'Jobs have owner, retry policy, timeout, idempotency key, and failure state.',
    moduleImpact: 'A source change can safely become a review queue item, CAPA draft, supplier packet, or KPI story.',
  },
  {
    id: 'tool-fabric',
    name: 'Tool and connector fabric',
    productUse: 'Give agents and modules controlled access to Gmail, Drive, Sheets, ERP exports, and browser tasks.',
    stack: ['MCP servers', 'Google Workspace APIs', 'Airbyte', 'Playwright or browser-use'],
    control: 'Tools are scoped by tenant, role, source owner, and writeback approval.',
    moduleImpact: 'The portal can work from real client data while keeping sensitive actions behind policy.',
  },
  {
    id: 'company-memory',
    name: 'Company memory layer',
    productUse: 'Make files, messages, sheets, decisions, entities, and KPIs reusable.',
    stack: ['Postgres', 'pgvector', 'file search or vector stores', 'knowledge graph'],
    control: 'Every answer links back to source, revision, owner, and access scope.',
    moduleImpact: 'Each new client portal improves over time as the system learns how the company organizes work.',
  },
  {
    id: 'evals-policy',
    name: 'Evals, guardrails, and policy gates',
    productUse: 'Stop weak agent outputs from becoming business records.',
    stack: ['OpenAI Evals', 'NIST AI RMF controls', 'policy engine', 'approval ledger'],
    control: 'High-risk outputs need human approval, test evidence, and rollback notes.',
    moduleImpact: 'Enterprise users can trust AI support without letting it silently mutate operations.',
  },
  {
    id: 'operating-intelligence',
    name: 'Operating intelligence mart',
    productUse: 'Convert workflow history into predictions, anomaly alerts, and next-best actions.',
    stack: ['DuckDB', 'dbt-style transforms', 'feature marts', 'OpenTelemetry'],
    control: 'Feature sources, formulas, thresholds, and freshness are visible.',
    moduleImpact: 'Modules become consequential because they measure action, not just store records.',
  },
]

export function getModuleContractsForPortal(portal: PortalModuleContract['portal']) {
  if (portal === 'industrial') return INDUSTRIAL_MODULE_CONTRACTS
  if (portal === 'restaurant') return RESTAURANT_MODULE_CONTRACTS
  return SERVICE_MODULE_CONTRACTS
}
