export const YTF_ERP_MODULE_IDS = [
  'inventory-ledger',
  'production-orders',
  'procurement-control',
  'finance-costing',
  'qms-capa-traceability',
  'hr-admin-planning',
  'agent-job-ledger',
] as const

export type YtfErpModuleId = (typeof YTF_ERP_MODULE_IDS)[number]

export type YtfErpRecordStatus =
  | 'draft'
  | 'needs-review'
  | 'active'
  | 'blocked'
  | 'approved'
  | 'closed'
  | 'archived'

export type YtfErpApprovalState =
  | 'not-required'
  | 'human-review-required'
  | 'approved'
  | 'rejected'
  | 'superseded'

export type YtfErpRole =
  | 'operator'
  | 'supervisor'
  | 'plant-manager'
  | 'admin'
  | 'quality'
  | 'maintenance'
  | 'procurement'
  | 'finance'
  | 'sales'
  | 'director'
  | 'ai-agent'

export type YtfErpSourceSystem =
  | 'manager-entry'
  | 'google-drive'
  | 'source-register'
  | 'workbook-extraction'
  | 'gmail'
  | 'bot-or-chat'
  | 'manual-import'
  | 'agent-run'

export type YtfErpSourceRef = {
  system: YtfErpSourceSystem
  sourceId: string
  sourceTitle: string
  sourceUrl?: string
  sheetName?: string
  rowRef?: string
  modifiedAt?: string
  extractionProfile?: string
  confidence?: 'low' | 'medium' | 'high'
}

export type YtfErpAuditTrailEntry = {
  at: string
  actorRole: YtfErpRole
  actorLabel: string
  action: string
  beforeStatus?: YtfErpRecordStatus
  afterStatus?: YtfErpRecordStatus
  evidenceRef?: string
}

export type YtfErpRecordBase = {
  id: string
  workspaceId: 'ytf-plant-a' | 'ytf-plant-b' | 'ytf-shared'
  moduleId: YtfErpModuleId
  ownerRole: YtfErpRole
  ownerLabel: string
  status: YtfErpRecordStatus
  approvalState: YtfErpApprovalState
  priority: 'low' | 'normal' | 'high' | 'critical'
  eventAt?: string
  dueAt?: string
  sourceRefs: YtfErpSourceRef[]
  auditTrail: YtfErpAuditTrailEntry[]
  humanApprovalGates: string[]
  createdAt: string
  updatedAt: string
}

export type YtfErpFieldContract = {
  key: string
  label: string
  required: boolean
  sourceHint: string
}

export type YtfErpApiContract = {
  read: string
  write: string
  review: string
  export: string
}

export type YtfErpModuleContract = {
  id: YtfErpModuleId
  title: string
  route: string
  phase: 'contract-ready' | 'mvp-next' | 'expansion'
  ownerRoles: YtfErpRole[]
  canonicalRecords: string[]
  requiredFields: YtfErpFieldContract[]
  sourceSystems: YtfErpSourceSystem[]
  api: YtfErpApiContract
  humanApprovalGates: string[]
  acceptanceChecks: string[]
}

export type YtfErpFeatureContract = {
  id: string
  title: string
  status: string
  route: string
  value: string
  detail: string
  acceptance: string
}

export type YtfErpFixQueueItem = {
  id: string
  title: string
  riskLabel: string
  owner: string
  route: string
  risk: string
  fix: string
  acceptance: string
}

export type YtfErpFinalizationStep = {
  id: string
  title: string
  owner: string
  route: string
  decision: string
  doneWhen: string
}

export type YtfErpPremiumUpgradeLane = {
  id: string
  title: string
  priority: 'P0' | 'P1' | 'P2'
  route: string
  missing: string
  build: string
  premiumStandard: string
  aiNativeEdge: string
  acceptance: string
}

export type YtfErpAiWorkerContract = {
  id: string
  title: string
  route: string
  accessScope: string
  tools: string[]
  humanGate: string
  output: string
  safety: string
}

export type YtfErpSynthesisPoint = {
  id: string
  title: string
  label: string
  detail: string
  decision: string
}

export type YtfErpEnterpriseAuditNote = {
  id: string
  area: string
  currentState: string
  gap: string
  implementation: string
  enterpriseStandard: string
  nextEvidence: string
}

export type YtfErpIterationRoadmapItem = {
  pass: number
  title: string
  status: 'live' | 'implemented-next' | 'build-next'
  focus: string
  implemented: string
  nextBuild: string
  doneWhen: string
}

export type YtfErpWcmLoop = {
  id: string
  title: string
  route: string
  factoryRitual: string
  systemRecord: string
  aiSupport: string
  reviewGate: string
}

export const YTF_ERP_SHARED_REQUIRED_FIELDS = [
  { key: 'id', label: 'Stable record id', required: true, sourceHint: 'Generated by the module API.' },
  { key: 'workspaceId', label: 'Workspace scope', required: true, sourceHint: 'Factory Floor, Plant B, or shared company scope.' },
  { key: 'moduleId', label: 'Module id', required: true, sourceHint: 'One of the YTF ERP module ids.' },
  { key: 'ownerRole', label: 'Owner role', required: true, sourceHint: 'Human or agent role accountable for next action.' },
  { key: 'ownerLabel', label: 'Owner label', required: true, sourceHint: 'Team, person, or queue visible to operators.' },
  { key: 'status', label: 'Record status', required: true, sourceHint: 'Draft, review, active, blocked, approved, closed, or archived.' },
  { key: 'approvalState', label: 'Approval state', required: true, sourceHint: 'Human gate before sensitive writeback or official KPI promotion.' },
  { key: 'sourceRefs', label: 'Evidence references', required: true, sourceHint: 'Workbook, manager entry, message, or automation evidence.' },
  { key: 'auditTrail', label: 'Audit trail', required: true, sourceHint: 'Every material status or owner change.' },
] satisfies readonly YtfErpFieldContract[]

export const YTF_ERP_KEY_FEATURES = [
  {
    id: 'transaction-spine',
    title: 'Transaction spine',
    status: 'Live cockpit',
    route: '/app/erp',
    value: '7 modules',
    detail: 'Inventory, production, QMS, procurement, finance, HR, and automation jobs share one record model.',
    acceptance: 'Every module has canonical records, required fields, APIs, approval gates, and acceptance checks.',
  },
  {
    id: 'source-graph',
    title: 'Source graph',
    status: 'Live evidence',
    route: '/app/live-data?view=database',
    value: 'Source-backed',
    detail: 'Drive, workbook, manual entry, bot, Gmail, and agent outputs stay attached to ERP records.',
    acceptance: 'Every promoted record keeps evidence references and an audit-trail entry.',
  },
  {
    id: 'approval-ledger',
    title: 'Approval ledger',
    status: 'Human gated',
    route: '/app/action-board',
    value: 'No silent writeback',
    detail: 'Sensitive ERP moves wait for role-safe human approval before official company state changes.',
    acceptance: 'Writeback, KPI promotion, closeout, release, finance, and external-message gates are explicit.',
  },
  {
    id: 'fact-ledger',
    title: 'ERP fact ledger',
    status: 'Operating metric layer',
    route: '/app/live-data?view=kpi',
    value: 'Facts + KPIs',
    detail: 'Extracted operational facts become management metrics only after source and owner review.',
    acceptance: 'Official KPIs are separated from candidate facts and preserve source lineage.',
  },
  {
    id: 'role-cockpit',
    title: 'Role cockpit',
    status: 'Manager first',
    route: '/app/plant-manager',
    value: 'Plant roles',
    detail: 'Operators, supervisors, quality, plant managers, finance, directors, and agents see their work surface.',
    acceptance: 'Role screens expose the next action without exposing unrelated sensitive state.',
  },
  {
    id: 'agent-job-ledger',
    title: 'Agent job ledger',
    status: 'Governed automation',
    route: '/app/ai-stack',
    value: 'Reviewed jobs',
    detail: 'System jobs can read business records, propose work, and queue writeback, but they do not mutate final ERP state alone.',
    acceptance: 'Every automation run has record scope, tool scope, evidence, reviewer decision, eval result, and rollback path.',
  },
] satisfies readonly YtfErpFeatureContract[]

export const YTF_ERP_ENTERPRISE_AUDIT_NOTES = [
  {
    id: 'core-ledger-depth',
    area: 'Core ERP ledger depth',
    currentState: 'YTF has a governed transaction spine, evidence-backed facts, module contracts, and approval gates.',
    gap: 'The product still needs hardened create, amend, cancel, close, export, rollback, and period-lock behavior per module.',
    implementation: 'Added the premium upgrade map and module transaction engine lane so every module now has a visible enterprise gap and acceptance standard.',
    enterpriseStandard: 'SAP-class ERP must have stable master data, transactional records, auditability, authorization, close cycles, and controlled exception handling.',
    nextEvidence: 'First production-grade inventory movement API with append-only journal, balance derivation, export, and approval history.',
  },
  {
    id: 'manufacturing-control',
    area: 'Manufacturing execution and WCM',
    currentState: 'Plant manager, daily entry, QMS, action board, record graph, and ERP cockpit are connected in the YTF shell.',
    gap: 'The app needs stronger WCM daily management loops: visual boards, abnormality escalation, autonomous maintenance, 5S, safety, skills, and continuous improvement.',
    implementation: 'Added WCM operating loops so daily routines, abnormalities, quality holds, and maintenance events have explicit system records and AI support.',
    enterpriseStandard: 'A manufacturing ERP must connect planning, execution, quality, maintenance, labor, materials, and shop-floor feedback in real time.',
    nextEvidence: 'Mobile daily entry produces a WCM event that appears on the action board with owner, due date, evidence, and close gate.',
  },
  {
    id: 'ai-native-governance',
    area: 'AI-native governance',
    currentState: 'AI worker architecture exists with named workers, scopes, tools, human gates, outputs, and safety constraints.',
    gap: 'Workers need persisted job runs, eval scores, reviewer decisions, tool-call traces, and rollback packets before they are production autonomy.',
    implementation: 'Added explicit worker contracts and an AI stack route in the YTF app shell, then fixed route access so admin can open it.',
    enterpriseStandard: 'AI in ERP must be grounded in trusted business data, process context, permissions, observability, and governance.',
    nextEvidence: 'A record-intake worker run creates reviewed import mappings and blocked writeback until approval.',
  },
  {
    id: 'integration-data-fabric',
    area: 'Integration and data fabric',
    currentState: 'Workbook extraction, operating records, KPI candidates, and ERP facts are visible in the cockpit.',
    gap: 'Premium ERP needs record freshness, dedupe, import templates, schema drift detection, owner SLAs, and connector failure tasks.',
    implementation: 'Added integration fabric as a P0 upgrade lane tied to record freshness and visible owner tasks.',
    enterpriseStandard: 'Enterprise systems must know which record is trusted, when it was synced, who owns it, and what happens when it breaks.',
    nextEvidence: 'Stale record creates an action-board task and blocks official KPI promotion.',
  },
  {
    id: 'security-access',
    area: 'Security, access, and audit',
    currentState: 'YTF has private login, role-based shell, tenant route restrictions, and protected app surfaces.',
    gap: 'Shared starter access must move to named users, role review, sensitive export controls, and actor-specific approval trails.',
    implementation: 'Added role security and audit depth as a P0 lane and tied users to platform-admin until named-user screens are ready.',
    enterpriseStandard: 'Every sensitive read, write, approval, export, sync, and automation job must have actor, role, reason, time, and evidence.',
    nextEvidence: 'Named user activation flow with permission matrix and access-review approval.',
  },
  {
    id: 'reliability-release',
    area: 'Reliability and release operations',
    currentState: 'YTF deploy path verifies static output, API function, cron manifest, login, and domain contract.',
    gap: 'Production ERP still needs visible backup evidence, queue depth, replay controls, incident notes, sync lag, and rollback evidence.',
    implementation: 'Added observability, backups, and release controls as a premium lane and kept the deploy audits in the verification path.',
    enterpriseStandard: 'No production ERP release should be trusted without health, backup, deploy, monitoring, and rollback evidence.',
    nextEvidence: 'Platform admin reports backup freshness, cron status, failed job replay, deployment id, and current blockers.',
  },
] satisfies readonly YtfErpEnterpriseAuditNote[]

export const YTF_ERP_PREMIUM_SYNTHESIS = [
  {
    id: 'thesis',
    title: 'Traditional ERP',
    label: 'Thesis',
    detail: 'Strong ledgers, permissions, and audit trails, but heavy setup and weak day-to-day adoption on the factory floor.',
    decision: 'Keep transaction discipline, accounting-grade evidence, role permissions, and repeatable close cycles.',
  },
  {
    id: 'antithesis',
    title: 'Agent-only automation',
    label: 'Antithesis',
    detail: 'Fast data work and flexible copilots, but unsafe if automations can mutate business state without evidence, review, or rollback.',
    decision: 'Keep agent speed for extraction, cleanup, exception discovery, drafts, summaries, and suggested writeback.',
  },
  {
    id: 'synthesis',
    title: 'AI-native ERP',
    label: 'Synthesis',
    detail: 'Transaction-safe ERP with evidence-first AI workers that prepare work, explain gaps, and wait for human approval before official state changes.',
    decision: 'Build YTF as the premium operating system: record graph, transaction APIs, approval gates, automation job ledger, and role cockpits.',
  },
] satisfies readonly YtfErpSynthesisPoint[]

export const YTF_ERP_PREMIUM_UPGRADE_LANES = [
  {
    id: 'transaction-engine',
    title: 'Module transaction engine',
    priority: 'P0',
    route: '/app/erp',
    missing: 'The cockpit defines records, but every module still needs hardened create, review, close, export, and rollback paths.',
    build: 'Promote inventory, production, QMS, finance, procurement, HR, and automation jobs into versioned transaction APIs with validators.',
    premiumStandard: 'Append-only movement journals, immutable audit trails, idempotent imports, and exportable ledgers.',
    aiNativeEdge: 'Automations draft transactions from business evidence, but humans approve official state changes.',
    acceptance: 'Each module can create, review, approve, export, and trace records without overwriting operating history.',
  },
  {
    id: 'role-security-audit',
    title: 'Role security and audit depth',
    priority: 'P0',
    route: '/app/users',
    missing: 'Shared starter access is useful for rollout, but premium ERP needs named users, scoped permissions, and sensitive export controls.',
    build: 'Finalize named accounts, department role matrix, approval authority, auditTrail actor rules, and export visibility gates.',
    premiumStandard: 'Every sensitive read, write, approval, sync, export, and automation run carries actor, role, timestamp, evidence, and reason.',
    aiNativeEdge: 'Agents inherit least-privilege tool scopes and cannot self-approve privileged work.',
    acceptance: 'No approval, finance export, payroll correction, or writeback can occur without a named actor or delegated role.',
  },
  {
    id: 'mobile-plant-capture',
    title: 'Mobile plant capture',
    priority: 'P0',
    route: '/app/daily-entry',
    missing: 'Managers need phone/tablet data capture for board photos, inspections, receiving, stock movements, downtime, and daily close.',
    build: 'Create fast mobile forms with offline-tolerant drafts, photo evidence, role defaults, and QR/item lookup where useful.',
    premiumStandard: 'Shop-floor entry must be faster than spreadsheets while preserving evidence and review state.',
    aiNativeEdge: 'AI normalizes messy notes and images into draft records with confidence and required missing fields.',
    acceptance: 'An operator can submit an issue, stock event, or QC hold from mobile and see it in the review queue.',
  },
  {
    id: 'integration-fabric',
    title: 'Connector and source integration fabric',
    priority: 'P0',
    route: '/app/live-data?view=database',
    missing: 'Workbook ingestion is strong, but premium ERP needs configurable connectors, import profiles, dedupe, and sync health.',
    build: 'Add connector registry, record freshness SLAs, import templates, duplicate detection, and sync failure tasks.',
    premiumStandard: 'Every external record lane has owner, cadence, schema, freshness, last sync, error state, and promotion rule.',
    aiNativeEdge: 'Workers classify records, detect schema drift, and propose import mappings before data enters ERP.',
    acceptance: 'A stale or broken record lane creates a visible owner task and cannot silently degrade official reporting.',
  },
  {
    id: 'ai-worker-runtime',
    title: 'AI worker runtime',
    priority: 'P0',
    route: '/app/ai-stack',
    missing: 'The automation job ledger is governed, but the premium build needs named workers with access scopes, evals, queues, and rollback.',
    build: 'Define worker contracts for record intake, DQ, inventory reconciliation, QMS, production close, finance costing, and admin setup.',
    premiumStandard: 'Workers run with explicit record scope, tool scope, output schema, eval criteria, human gate, and rollback path.',
    aiNativeEdge: 'Agents become accountable knowledge workers that prepare real ERP work, not chatbot sidecars.',
    acceptance: 'Every automation job produces evidence, proposed action, confidence, reviewer decision, and retained run history.',
  },
  {
    id: 'semantic-kpi-layer',
    title: 'Semantic KPI and BI layer',
    priority: 'P1',
    route: '/app/data-quality',
    missing: 'The fact ledger has strong evidence, but premium ERP needs official metric definitions, owner rules, time windows, and variance stories.',
    build: 'Create semantic metric contracts for OEE, defects, claims, stock turns, production plan attainment, cost of poor quality, and cash exposure.',
    premiumStandard: 'Candidate facts, official KPIs, and executive reports stay separated until owner approval.',
    aiNativeEdge: 'AI explains changes, flags missing context, and writes manager-ready narratives from governed facts.',
    acceptance: 'A KPI cannot appear as official unless definition, owner, record references, period, and approval state are complete.',
  },
  {
    id: 'workflow-approvals',
    title: 'Workflow orchestration and approval UX',
    priority: 'P1',
    route: '/app/action-board',
    missing: 'Approval gates exist, but users need clean queues, escalation, due dates, comments, attachments, and status history.',
    build: 'Upgrade the action board into a module-aware approval center with filters, priority, SLA, owner handoff, and batch review.',
    premiumStandard: 'Every exception has owner, due date, evidence, decision, and visible business impact.',
    aiNativeEdge: 'Agents prepare recommended decisions and supporting evidence, but do not close gates alone.',
    acceptance: 'A manager can review, request evidence, approve, reject, or escalate from one role-safe queue.',
  },
  {
    id: 'observability-release-controls',
    title: 'Observability, backups, and release controls',
    priority: 'P1',
    route: '/app/platform-admin',
    missing: 'Premium ERP needs runtime health, database backup evidence, cron checks, failed job replay, and environment/release visibility.',
    build: 'Expose health checks, deployment ID, cron readiness, sync lag, queue depth, backup status, and safe rollback notes in admin.',
    premiumStandard: 'No production release is considered ready without health, backup, deploy, and rollback evidence.',
    aiNativeEdge: 'Ops agents monitor failures, summarize incidents, and open repair tasks without mutating production data.',
    acceptance: 'Admin can see whether the system is safe to run today and what is blocking production trust.',
  },
] satisfies readonly YtfErpPremiumUpgradeLane[]

export const YTF_ERP_AI_WORKER_ARCHITECTURE = [
  {
    id: 'source-intake-worker',
    title: 'Record Intake Worker',
    route: '/app/live-data?view=database',
    accessScope: 'Drive files, workbook rows, Gmail candidates, manual imports, and source registry metadata.',
    tools: ['classify source', 'detect schema drift', 'propose import profile'],
    humanGate: 'source promotion approval',
    output: 'Draft operating records and import mappings for review.',
    safety: 'Read-only until a data manager approves source promotion.',
  },
  {
    id: 'data-quality-worker',
    title: 'Data Quality Worker',
    route: '/app/data-quality',
    accessScope: 'Candidate facts, KPI definitions, evidence references, confidence scores, and missing-field queues.',
    tools: ['dedupe', 'validate units', 'flag missing owners'],
    humanGate: 'official KPI promotion approval',
    output: 'Cleaned candidates, rejected rows, and promotion recommendations.',
    safety: 'Cannot mark a KPI official without owner approval.',
  },
  {
    id: 'inventory-reconciliation-worker',
    title: 'Inventory Reconciliation Worker',
    route: '/app/live-data?view=kpi&scope=stock',
    accessScope: 'Stock facts, receiving records, movement journals, adjustments, holds, and item/location masters.',
    tools: ['match movement evidence', 'find variance', 'draft adjustment'],
    humanGate: 'stock adjustment approval',
    output: 'Variance packet with proposed stock movement and evidence.',
    safety: 'Cannot release holds or change balances directly.',
  },
  {
    id: 'production-close-worker',
    title: 'Production Close Worker',
    route: '/app/plant-manager',
    accessScope: 'Production orders, actual output, scrap/rework, downtime, QC exceptions, and daily close entries.',
    tools: ['compare plan to actual', 'link quality exceptions', 'draft closeout'],
    humanGate: 'production close approval',
    output: 'Closeout packet with blockers, actuals, exceptions, and reviewer action.',
    safety: 'Cannot close an order with unresolved quality or evidence gaps.',
  },
  {
    id: 'qms-capa-worker',
    title: 'QMS and CAPA Worker',
    route: '/app/dqms',
    accessScope: 'Inspection results, nonconformance, containment, root cause, release decisions, and supplier evidence.',
    tools: ['draft 5W1H', 'group recurring defects', 'prepare CAPA follow-up'],
    humanGate: 'root-cause close review',
    output: 'CAPA packet with evidence, owner, due date, and verification step.',
    safety: 'Cannot release product or close root cause without quality approval.',
  },
  {
    id: 'finance-costing-worker',
    title: 'Finance Costing Worker',
    route: '/app/revenue',
    accessScope: 'Cost events, purchase exposure, claims, scrap, downtime, payroll-impacting adjustments, and finance approvals.',
    tools: ['estimate COPQ', 'link operational cause', 'draft finance review'],
    humanGate: 'official cost approval',
    output: 'Cost impact packet with assumption, source, and approval state.',
    safety: 'Cannot expose sensitive finance details outside approved roles.',
  },
  {
    id: 'admin-role-worker',
    title: 'Admin Role Worker',
    route: '/app/users',
    accessScope: 'Users, role matrix, starter accounts, permissions, approval authority, and access review tasks.',
    tools: ['detect shared account risk', 'suggest role split', 'draft onboarding checklist'],
    humanGate: 'role access approval',
    output: 'Role change proposal with reason, scope, and rollback.',
    safety: 'Cannot grant access directly; admin approves every activation.',
  },
] satisfies readonly YtfErpAiWorkerContract[]

export const YTF_ERP_10X_ITERATION_ROADMAP = [
  {
    pass: 1,
    title: 'Source of truth and evidence',
    status: 'live',
    focus: 'Workbook, manual entry, message, and automation outputs must stay attached to evidence references.',
    implemented: 'Record graph, operating records, review signals, KPI candidates, and ERP facts are visible on the cockpit.',
    nextBuild: 'Add stale-source SLA tasks and source-owner assignment.',
    doneWhen: 'Every official ERP record has evidence references, confidence, owner, and freshness state.',
  },
  {
    pass: 2,
    title: 'Transaction engine',
    status: 'implemented-next',
    focus: 'Create module APIs that enforce journal, close, approval, export, and rollback rules.',
    implemented: 'Module contracts and premium transaction-engine lane define the target behavior.',
    nextBuild: 'Ship the inventory movement journal as the first hardened transaction API.',
    doneWhen: 'Stock balance is derived only from append-only movements and approved adjustments.',
  },
  {
    pass: 3,
    title: 'Master data discipline',
    status: 'build-next',
    focus: 'Items, locations, suppliers, users, work centers, products, lots, and KPI definitions need stable IDs.',
    implemented: 'Shared required fields and module records define stable ids, workspace scope, owner, status, evidence references, and audit trail.',
    nextBuild: 'Add item/location/supplier/user master records with import validation and dedupe.',
    doneWhen: 'No transaction can be promoted without matching or creating a reviewed master record.',
  },
  {
    pass: 4,
    title: 'Mobile plant capture',
    status: 'implemented-next',
    focus: 'Operators and managers need fast phone/tablet capture for abnormalities, quality, stock, downtime, and daily close.',
    implemented: 'Daily entry and mobile plant capture lane are connected to WCM loops.',
    nextBuild: 'Add offline-tolerant draft state, photo evidence, and required missing-field prompts.',
    doneWhen: 'A shop-floor issue submitted on mobile becomes a reviewable action with evidence and owner.',
  },
  {
    pass: 5,
    title: 'WCM operating loops',
    status: 'implemented-next',
    focus: 'Daily management, 5S, safety, autonomous maintenance, quality, training, and focused improvement need closed loops.',
    implemented: 'WCM loop contracts define rituals, system records, AI support, and review gates.',
    nextBuild: 'Add a WCM event ledger and weekly loss-tree review packet.',
    doneWhen: 'Every abnormality has containment, owner, due date, learning, and close evidence.',
  },
  {
    pass: 6,
    title: 'Role security and audit',
    status: 'implemented-next',
    focus: 'Move from shared starter access to named users, delegated authority, audit trails, and export controls.',
    implemented: 'Role security lane and YTF route guard now include the AI stack only for admin-capable roles.',
    nextBuild: 'Add named-user activation and access-review queue.',
    doneWhen: 'Every approval, sensitive read, export, sync, and automation job is actor-attributed.',
  },
  {
    pass: 7,
    title: 'AI worker productionization',
    status: 'implemented-next',
    focus: 'Workers need scope, tools, output schemas, evals, reviewer gates, traces, and rollback.',
    implemented: 'Seven named AI worker contracts are visible from the ERP and open the AI stack.',
    nextBuild: 'Persist automation jobs with eval result, proposed writeback, reviewer decision, and rollback path.',
    doneWhen: 'AI can prepare ERP work but cannot self-approve official business state.',
  },
  {
    pass: 8,
    title: 'Integration fabric',
    status: 'build-next',
    focus: 'Every connector needs cadence, owner, schema, freshness, failure state, dedupe, and promotion rule.',
    implemented: 'Integration fabric lane is P0 and tied to record freshness and owner tasks.',
    nextBuild: 'Create connector registry and import-profile review screen.',
    doneWhen: 'Broken or stale connectors create owner tasks and block official reporting when needed.',
  },
  {
    pass: 9,
    title: 'Observability and release control',
    status: 'build-next',
    focus: 'Production trust needs health, backups, cron readiness, queue depth, sync lag, incident notes, and rollback.',
    implemented: 'Deploy path verifies build, function, domain, login, and route contract.',
    nextBuild: 'Expose runtime readiness and backup evidence in platform admin.',
    doneWhen: 'Admin can decide if the ERP is safe to run today from one production status panel.',
  },
  {
    pass: 10,
    title: 'Enterprise rollout and adoption',
    status: 'build-next',
    focus: 'World-class ERP succeeds only if the plant uses it daily and the system improves decisions faster than spreadsheets.',
    implemented: 'Role cockpits, action board, daily entry, live data, ERP cockpit, and AI stack are connected.',
    nextBuild: 'Add adoption score, weekly management ritual, training acknowledgements, and rollout checklist.',
    doneWhen: 'Each role has a daily work loop, measurable adoption, and manager-visible business impact.',
  },
] satisfies readonly YtfErpIterationRoadmapItem[]

export const YTF_ERP_WCM_OPERATING_LOOPS = [
  {
    id: 'daily-management',
    title: 'Daily Management',
    route: '/app/plant-manager',
    factoryRitual: 'Start-of-shift review, plan versus actual, staffing, safety, stock, quality, and blockers.',
    systemRecord: 'Daily plan, shift status, owner actions, KPI facts, and closeout note.',
    aiSupport: 'Summarize plan gaps, missing evidence, and high-risk actions for the manager.',
    reviewGate: 'Plant manager daily close approval.',
  },
  {
    id: 'abnormality-management',
    title: 'Abnormality Management',
    route: '/app/daily-entry?mode=normal_abnormal',
    factoryRitual: 'Capture abnormal condition, containment, owner, due date, and impact before the issue disappears.',
    systemRecord: 'Abnormality event, containment action, evidence references, priority, and action-board task.',
    aiSupport: 'Classify issue, suggest owner, and ask for missing fields or photo evidence.',
    reviewGate: 'Supervisor or quality close review.',
  },
  {
    id: 'quality-maintenance',
    title: 'Quality Maintenance',
    route: '/app/dqms',
    factoryRitual: 'Inspect, hold, contain, verify root cause, and release only after evidence is complete.',
    systemRecord: 'Inspection result, nonconformance, containment, CAPA, trace link, and release decision.',
    aiSupport: 'Draft 5W1H/CAPA packet and detect repeated defect patterns.',
    reviewGate: 'Release decision review and root-cause close review.',
  },
  {
    id: 'autonomous-maintenance',
    title: 'Autonomous Maintenance',
    route: '/app/daily-entry?mode=normal_abnormal&section=Maintenance',
    factoryRitual: 'Operators tag equipment abnormalities, basic care actions, downtime, and escalation needs.',
    systemRecord: 'Maintenance abnormality, downtime event, equipment note, owner task, and close evidence.',
    aiSupport: 'Group repeated equipment losses and draft maintenance follow-up.',
    reviewGate: 'Maintenance supervisor close approval.',
  },
  {
    id: 'focused-improvement',
    title: 'Focused Improvement',
    route: '/app/action-board',
    factoryRitual: 'Weekly loss review chooses the biggest recurring waste and assigns countermeasures.',
    systemRecord: 'Loss tree, improvement task, baseline KPI, countermeasure, owner, and result.',
    aiSupport: 'Rank recurring losses from ERP facts and operating records.',
    reviewGate: 'Manager accepts result or reopens countermeasure.',
  },
  {
    id: 'skills-and-training',
    title: 'Skills and Training',
    route: '/app/manager-system',
    factoryRitual: 'Confirm SOP acknowledgement, training needs, skill matrix, and role readiness.',
    systemRecord: 'Training action, SOP revision acknowledgement, skill record, and access gate.',
    aiSupport: 'Suggest training from recurring issues and role gaps.',
    reviewGate: 'Admin or manager training acknowledgement approval.',
  },
] satisfies readonly YtfErpWcmLoop[]

export const YTF_ERP_MODULE_CONTRACTS = [
  {
    id: 'inventory-ledger',
    title: 'Inventory Ledger',
    route: '/app/inventory',
    phase: 'mvp-next',
    ownerRoles: ['supervisor', 'plant-manager', 'admin', 'finance'],
    canonicalRecords: ['item master', 'lot or batch', 'location', 'stock movement', 'stock hold', 'cycle count', 'dispatch reservation'],
    requiredFields: [
      { key: 'itemId', label: 'Item', required: true, sourceHint: 'Workbook item column, receiving entry, or item master.' },
      { key: 'movementType', label: 'Movement type', required: true, sourceHint: 'Receipt, issue, transfer, adjustment, hold, release, or dispatch.' },
      { key: 'quantity', label: 'Quantity', required: true, sourceHint: 'Workbook numeric sample or manager entry.' },
      { key: 'unit', label: 'Unit', required: true, sourceHint: 'Workbook header, item master, or owner-confirmed unit.' },
      { key: 'locationId', label: 'Location', required: true, sourceHint: 'Warehouse, line, store, showroom, or bin.' },
    ],
    sourceSystems: ['manager-entry', 'google-drive', 'workbook-extraction', 'manual-import', 'agent-run'],
    api: {
      read: 'GET /api/inventory/records',
      write: 'POST /api/inventory/records',
      review: 'POST /api/workspace-tasks',
      export: 'GET /api/inventory/records?format=csv',
    },
    humanApprovalGates: ['stock adjustment approval', 'hold release approval', 'finance valuation approval'],
    acceptanceChecks: ['append-only stock movements', 'balance derives from movement journal', 'receiving variance can create hold', 'every movement has evidence'],
  },
  {
    id: 'production-orders',
    title: 'Production Orders',
    route: '/app/plant-manager',
    phase: 'mvp-next',
    ownerRoles: ['operator', 'supervisor', 'plant-manager', 'quality', 'maintenance'],
    canonicalRecords: ['production order', 'work center', 'stage confirmation', 'scrap or rework', 'downtime event', 'order closeout'],
    requiredFields: [
      { key: 'orderId', label: 'Production order', required: true, sourceHint: 'Planner entry, workbook row, or generated daily plan.' },
      { key: 'productSpec', label: 'Product/spec', required: true, sourceHint: 'Workbook header, plan row, or product master.' },
      { key: 'plannedQuantity', label: 'Planned quantity', required: true, sourceHint: 'Plan workbook or manager entry.' },
      { key: 'actualQuantity', label: 'Actual quantity', required: true, sourceHint: 'Whiteboard, workbook, or daily close entry.' },
      { key: 'stageStatus', label: 'Stage status', required: true, sourceHint: 'Open, running, blocked, confirmed, or closed.' },
    ],
    sourceSystems: ['manager-entry', 'google-drive', 'workbook-extraction', 'bot-or-chat', 'agent-run'],
    api: {
      read: 'GET /api/metrics/records?module=production-orders',
      write: 'POST /api/ytf/data-manager/run',
      review: 'POST /api/tools/action-board',
      export: 'GET /api/metrics/records?module=production-orders&format=csv',
    },
    humanApprovalGates: ['production close approval', 'scrap approval', 'quality exception approval'],
    acceptanceChecks: ['planned to in-progress to confirmed to closed path', 'actual output and reject fields captured', 'quality and maintenance exceptions link to order'],
  },
  {
    id: 'procurement-control',
    title: 'Procurement and Supplier Control',
    route: '/app/receiving',
    phase: 'expansion',
    ownerRoles: ['procurement', 'finance', 'quality', 'admin'],
    canonicalRecords: ['supplier', 'purchase order', 'PO line', 'GRN', 'supplier document', 'receiving variance', 'supplier case'],
    requiredFields: [
      { key: 'supplierId', label: 'Supplier', required: true, sourceHint: 'Supplier sheet, invoice, PO, or email thread.' },
      { key: 'documentState', label: 'Document state', required: true, sourceHint: 'COA, invoice, GRN, payment evidence, or missing document task.' },
      { key: 'varianceReason', label: 'Variance reason', required: false, sourceHint: 'Receiving hold, QC issue, or owner note.' },
      { key: 'approvalOwner', label: 'Approval owner', required: true, sourceHint: 'Procurement, quality, finance, or admin.' },
    ],
    sourceSystems: ['google-drive', 'gmail', 'workbook-extraction', 'manager-entry', 'agent-run'],
    api: {
      read: 'GET /api/receiving/records',
      write: 'POST /api/receiving/records',
      review: 'POST /api/approvals',
      export: 'GET /api/receiving/records?format=csv',
    },
    humanApprovalGates: ['supplier escalation approval', 'payment evidence approval', 'quality document acceptance'],
    acceptanceChecks: ['receiving hold links to PO or supplier evidence', 'missing COA creates owner action', 'approval records actor and timestamp'],
  },
  {
    id: 'finance-costing',
    title: 'Finance and Costing',
    route: '/app/revenue',
    phase: 'expansion',
    ownerRoles: ['finance', 'director', 'admin'],
    canonicalRecords: ['cost driver', 'cost event', 'COPQ packet', 'purchase exposure', 'claim cost', 'margin snapshot'],
    requiredFields: [
      { key: 'costCenter', label: 'Cost center', required: true, sourceHint: 'Finance sheet, owner rule, or approved cost model.' },
      { key: 'costDriver', label: 'Cost driver', required: true, sourceHint: 'Scrap, downtime, claim, purchase, labor, utility, or rework.' },
      { key: 'amount', label: 'Amount or estimate', required: true, sourceHint: 'Workbook value, approved assumption, or finance entry.' },
      { key: 'approvalState', label: 'Finance approval', required: true, sourceHint: 'Finance confirmation before official reporting.' },
    ],
    sourceSystems: ['google-drive', 'workbook-extraction', 'gmail', 'manual-import', 'agent-run'],
    api: {
      read: 'GET /api/metrics/records?module=finance-costing',
      write: 'POST /api/ytf/data-manager/run',
      review: 'POST /api/approvals',
      export: 'GET /api/metrics/records?module=finance-costing&format=csv',
    },
    humanApprovalGates: ['official cost approval', 'payment action approval', 'sensitive finance visibility approval'],
    acceptanceChecks: ['cost KPI cannot be official without source lineage', 'finance role gates sensitive details', 'COPQ packet links operational cause to money impact'],
  },
  {
    id: 'qms-capa-traceability',
    title: 'QMS, CAPA, and Traceability',
    route: '/app/daily-entry?mode=normal_abnormal&section=QC%20%2F%20inspection',
    phase: 'mvp-next',
    ownerRoles: ['quality', 'plant-manager', 'operator', 'admin'],
    canonicalRecords: ['inspection order', 'inspection result', 'nonconformance', 'containment', 'root-cause follow-up', 'release decision', 'trace link'],
    requiredFields: [
      { key: 'inspectionScope', label: 'Inspection scope', required: true, sourceHint: 'Product, process, supplier, claim, or batch scope.' },
      { key: 'result', label: 'Result', required: true, sourceHint: 'Pass, fail, hold, rework, release, or blocked.' },
      { key: 'containmentAction', label: 'Containment action', required: false, sourceHint: 'Immediate action when nonconformance exists.' },
      { key: 'verificationOwner', label: 'Verifier', required: true, sourceHint: 'Quality owner for root-cause or release close.' },
    ],
    sourceSystems: ['manager-entry', 'google-drive', 'workbook-extraction', 'manual-import', 'agent-run'],
    api: {
      read: 'GET /api/quality/incidents',
      write: 'POST /api/quality/incidents',
      review: 'POST /api/quality/follow-up',
      export: 'GET /api/quality/incidents?format=csv',
    },
    humanApprovalGates: ['release decision review', 'root-cause close review', 'supplier quality acceptance'],
    acceptanceChecks: ['failed inspection can open nonconformance', 'root-cause follow-up has cause and verifier', 'trace pack links evidence where data exists'],
  },
  {
    id: 'hr-admin-planning',
    title: 'HR, Attendance, OT, and Payroll',
    route: '/app/attendance-payroll',
    phase: 'expansion',
    ownerRoles: ['admin', 'plant-manager', 'director', 'finance'],
    canonicalRecords: ['user', 'role', 'employee', 'face enrollment', 'shift', 'attendance event', 'daily attendance summary', 'OT claim', 'payroll adjustment', 'skill matrix', 'SOP acknowledgement', 'training action'],
    requiredFields: [
      { key: 'personOrRoleId', label: 'Person or role', required: true, sourceHint: 'Named user, starter account, team, or future HR source.' },
      { key: 'employeeCode', label: 'Employee code', required: true, sourceHint: 'Employee Details sheet, salary workbook, or HR confirmation.' },
      { key: 'shiftOrTrainingScope', label: 'Shift/training scope', required: true, sourceHint: 'Attendance, OT, SOP, training, payroll period, or permission scope.' },
      { key: 'attendanceSource', label: 'Attendance source', required: true, sourceHint: 'Tablet check-in, phone check-in, ZKTeco export, or manual admin entry.' },
      { key: 'approvalState', label: 'Approval state', required: true, sourceHint: 'Face/photo match, supervisor OT approval, and payroll approval are separate gates.' },
      { key: 'acknowledgementState', label: 'Acknowledgement state', required: false, sourceHint: 'SOP or training acknowledgement.' },
      { key: 'permissionBoundary', label: 'Permission boundary', required: true, sourceHint: 'Role-safe access rule.' },
    ],
    sourceSystems: ['manager-entry', 'manual-import', 'google-drive', 'agent-run'],
    api: {
      read: 'GET /api/attendance/checkins',
      write: 'POST /api/attendance/checkins',
      review: 'POST /api/workspace-tasks',
      export: 'GET /api/attendance/payroll-export?format=csv',
    },
    humanApprovalGates: ['employee consent approval', 'low-confidence match review', 'OT supervisor approval', 'payroll period lock approval', 'named user activation approval'],
    acceptanceChecks: ['named users replace shared accounts after rollout', 'role matrix controls screens and data', 'SOP acknowledgement is revision-specific', 'face/photo event does not auto-pay without approval', 'every payroll-impacting correction has evidence and audit trail'],
  },
  {
    id: 'agent-job-ledger',
    title: 'Agent Job Ledger',
    route: '/app/ai-stack',
    phase: 'contract-ready',
    ownerRoles: ['admin', 'ai-agent', 'plant-manager', 'director'],
    canonicalRecords: ['automation job', 'record scope', 'tool scope', 'evidence list', 'proposed writeback', 'review decision', 'eval result', 'rollback path'],
    requiredFields: [
      { key: 'agentRunId', label: 'Automation run', required: true, sourceHint: 'Enterprise automation run id or background job id.' },
      { key: 'sourceScope', label: 'Source scope', required: true, sourceHint: 'Explicit files, folders, rows, routes, or records allowed.' },
      { key: 'toolScope', label: 'Tool scope', required: true, sourceHint: 'Allowed read/write tools for this run.' },
      { key: 'reviewDecision', label: 'Review decision', required: true, sourceHint: 'Human approval before customer-system mutation.' },
    ],
    sourceSystems: ['agent-run', 'google-drive', 'workbook-extraction', 'gmail', 'bot-or-chat'],
    api: {
      read: 'GET /api/agent-runs',
      write: 'POST /api/agent-runs/process-queue',
      review: 'POST /api/workspace-tasks',
      export: 'GET /api/agent-runs?format=csv',
    },
    humanApprovalGates: ['external message approval', 'finance writeback approval', 'production close approval', 'KPI promotion approval'],
    acceptanceChecks: ['every automation output has record scope', 'writeback waits for reviewer', 'eval failures create review tasks', 'promoted records link to automation run'],
  },
] satisfies readonly YtfErpModuleContract[]

export const YTF_ERP_HUMAN_APPROVAL_GATES = [
  'production close approval',
  'release decision review',
  'root-cause close review',
  'payment action approval',
  'official KPI promotion approval',
  'external message approval',
  'role access approval',
] as const

export const YTF_ERP_FIX_QUEUE = [
  {
    id: 'cloud-database-writeback',
    title: 'Verify cloud database before official writeback',
    riskLabel: 'Blocker',
    owner: 'Platform admin',
    route: '/app/platform-admin',
    risk: 'ERP state cannot be trusted if the tenant falls back to a local or missing database during release.',
    fix: 'Confirm SUPERMEGA_DATABASE_URL, direct Postgres fallback, and saved row counts after the YTF sync loop.',
    acceptance: 'The command center reports a configured database and a timestamped refresh with saved records.',
  },
  {
    id: 'official-kpi-promotion',
    title: 'Separate candidate facts from official KPIs',
    riskLabel: 'Control',
    owner: 'Data manager',
    route: '/app/data-quality',
    risk: 'Extracted numbers can look official before a human owner validates definition, source, and period.',
    fix: 'Use the data-quality queue to approve KPI definitions and keep rejected or draft candidates out of executive totals.',
    acceptance: 'Official KPI count is visible and every official metric has evidence.',
  },
  {
    id: 'inventory-movement-journal',
    title: 'Lock append-only inventory movement rules',
    riskLabel: 'Inventory',
    owner: 'Plant manager',
    route: '/app/live-data?view=kpi&scope=stock',
    risk: 'Stock balances can drift if inventory edits overwrite prior movement history.',
    fix: 'Finalize receiving, issue, transfer, hold, release, and adjustment event types with evidence references and approval gates.',
    acceptance: 'Balances derive from movement journal records and all adjustments have reviewer evidence.',
  },
  {
    id: 'production-quality-closeout',
    title: 'Tie production closeout to quality exceptions',
    riskLabel: 'Quality',
    owner: 'Quality lead',
    route: '/app/dqms',
    risk: 'Production can close while failed inspections, holds, or root-cause work remain unresolved.',
    fix: 'Link production order close, failed inspection, containment, root cause, and release decision records.',
    acceptance: 'A failed inspection creates an owner action and blocks release until review is recorded.',
  },
  {
    id: 'role-access-matrix',
    title: 'Replace shared-access habits with named roles',
    riskLabel: 'Access',
    owner: 'Admin',
    route: '/app/users',
    risk: 'Shared accounts and broad access hide who approved, edited, or exported sensitive ERP state.',
    fix: 'Finalize named users, role capability rules, starter accounts, and approval authority by department.',
    acceptance: 'Every approval and sensitive export carries an actor role, owner label, and auditTrail entry.',
  },
] satisfies readonly YtfErpFixQueueItem[]

export const YTF_ERP_FINALIZATION_STEPS = [
  {
    id: 'inventory-ledger-mvp',
    title: 'Finalize inventory ledger MVP',
    owner: 'Plant',
    route: '/app/live-data?view=kpi&scope=stock',
    decision: 'Confirm movement types, locations, lot/batch rules, hold release authority, and stock valuation visibility.',
    doneWhen: 'A manager can review stock movement evidence, approve an adjustment, and export the ledger.',
  },
  {
    id: 'production-order-close',
    title: 'Finalize production order closeout',
    owner: 'Operations',
    route: '/app/plant-manager',
    decision: 'Choose the first production-order workflow from plan, run, exception, actual output, and close approval.',
    doneWhen: 'Closeout records show planned quantity, actual quantity, scrap/rework, downtime, and reviewer.',
  },
  {
    id: 'qms-release-path',
    title: 'Finalize QMS hold and release path',
    owner: 'Quality',
    route: '/app/dqms',
    decision: 'Connect failed inspection, nonconformance, containment, root cause, verification, and release authority.',
    doneWhen: 'A held item cannot release until the QMS review and trace evidence are present.',
  },
  {
    id: 'erp-role-rollout',
    title: 'Finalize named-user role rollout',
    owner: 'Admin',
    route: '/app/users',
    decision: 'Confirm who can view, approve, export, sync, and write back for each ERP module.',
    doneWhen: 'Starter users and role capabilities replace shared account usage for live pilot workflows.',
  },
  {
    id: 'agent-worker-runtime',
    title: 'Finalize agent worker runtime',
    owner: 'AI ops',
    route: '/app/ai-stack',
    decision: 'Set record scope, tool scope, eval criteria, reviewer queue, rollback path, and approved mutation routes.',
    doneWhen: 'Agent jobs create reviewed ERP work items without bypassing human approval gates.',
  },
] satisfies readonly YtfErpFinalizationStep[]

export function findYtfErpModuleContract(moduleId: YtfErpModuleId) {
  return YTF_ERP_MODULE_CONTRACTS.find((contract) => contract.id === moduleId)
}

export function listYtfErpMvpModules() {
  return YTF_ERP_MODULE_CONTRACTS.filter((contract) => contract.phase === 'mvp-next')
}
