// SUPERMEGA connectors — single import point. Importing this side-effect-registers every
// built-in connector, then re-exports the registry API. Anything that wants the registry should
// `import connectors from '.../connectors/index.mjs'` so it can't accidentally miss an adapter.
//
// To add a connector: create connectors/<key>.mjs that calls register(...) at module load,
// then add one import line below. That's the whole wiring. See README.md.

import registry from './registry.mjs'

// Side-effect imports — each module calls register(...) when loaded.
import './ai-gateway.mjs'
import './data-supabase.mjs'
import './data-sheets.mjs'
import './data-drive.mjs'
import './data-gmail.mjs'
import './data-calendar.mjs'
import './payment-stripe.mjs'
import './payment-mmqr.mjs'
import './payment-kbzpay.mjs'
import './payment-wavepay.mjs'
import './messaging-resend.mjs'
import './messaging-slack.mjs'
import './messaging-telegram.mjs'
import './messaging-viber.mjs'
import './messaging-line.mjs'
import './messaging-line-notify.mjs'
import './messaging-facebook.mjs'
import './messaging-whatsapp.mjs'
import './messaging-sms.mjs'
import './integration-webhook.mjs'
import './payment-onepay.mjs'
import './payment-ayapay.mjs'
import './payment-cbpay.mjs'
import './messaging-teams.mjs'
import './data-notion.mjs'
import './commerce-shopify.mjs'
import './commerce-barcode.mjs'
import './data-cbm-rate.mjs'
import './ai-gemini.mjs'
import './ai-openai.mjs'
import './infra-http.mjs'
import './data-airtable.mjs'
import './ai-anthropic.mjs'
import './ai-openrouter.mjs'
import './messaging-discord.mjs'
import './commerce-woocommerce.mjs'
import './data-hubspot.mjs'
import './payment-2c2p.mjs'
import './commerce-shopee.mjs'
import './commerce-lazada.mjs'
import './ai-deepseek.mjs'
import './ai-mistral.mjs'
import './data-quickbooks.mjs'
import './integration-zapier.mjs'
import './data-mailchimp.mjs'
import './ai-groq.mjs'
import './ai-cohere.mjs'
import './messaging-instagram.mjs'
import './data-dropbox.mjs'
import './commerce-square.mjs'
import './data-xero.mjs'
import './commerce-tiktok-shop.mjs'
import './logistics-ninjavan.mjs'
import './logistics-jnt.mjs'
import './payment-dinger.mjs'
import './data-zoho-books.mjs'
import './ai-perplexity.mjs'
import './marketing-meta-ads.mjs'
import './data-ga4.mjs'
import './ai-together.mjs'
import './ai-fireworks.mjs'
import './data-onedrive.mjs'
import './data-box.mjs'
import './data-google-contacts.mjs'
import './messaging-zalo.mjs'
import './ai-vertex.mjs'
import './payment-paypal.mjs'
import './crm-pipedrive.mjs'
import './data-clickup.mjs'

export * from './registry.mjs'
export default registry
