// Actual customer UI, synthetic transport. Local QA only; never marketing imagery.
import { createRequire } from 'node:module'
import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
const root = fileURLToPath(new URL('..', import.meta.url))
const { build } = createRequire(resolve(root, 'showroom/package.json'))('esbuild')
const out = resolve(root, '.tmp/qa-workspaces'); mkdirSync(out, { recursive: true })
await build({ stdin: { resolveDir: resolve(root, 'showroom'), loader: 'tsx', contents: `
import React,{useMemo,useState} from 'react';import{createRoot}from'react-dom/client';
import{HostedSitePanel,HostedInquiryInbox}from'./src/products/website/HostedWebsite';
import'./src/products/website/website-product.css';
const id='11111111-1111-4111-8111-111111111111',digest='sha256:'+'a'.repeat(64);
const source={version:4,snapshotId:'synthetic-review',artifactDigest:digest};
const records=[{name:'Daw Su',contact:'qa@example.test',message:'မင်္ဂလာပါ။ လူ ၂၀ အတွက် စားပွဲ ကြိုတင်မှာယူချင်ပါတယ်။ ဈေးနှုန်း သိချင်ပါတယ်။',requestId:id},
{name:'Ko Min',contact:'synthetic@example.test',message:'Could you share your catering menu for an office lunch next Friday?',requestId:'22222222-2222-4222-8222-222222222222'},
{name:'May',contact:'sample@example.test',message:'Are you open on Sunday morning?',requestId:'33333333-3333-4333-8333-333333333333'}].map((r,i)=>({...r,channelId:id,siteName:'Corner Café · QA',sourcePage:'/contact',status:'new',revision:1,assignedTo:null,updatedBy:null,updatedAt:null,note:'',receivedAt:'2026-10-10T08:'+String(30-i*10).padStart(2,'0')+':00Z'}));
function App(){const[view,setView]=useState('inbox');const[mode,setMode]=useState('received');const client=useMemo(()=>{let publication=null;const data=structuredClone(records);return{
status:async()=>{if(mode==='failure')throw Error('Website hosting is not available for this workspace yet.');return{publicOrigin:'https://sites.example.test',source,publications:publication?[publication]:[]}},
publish:async(channel,page)=>{if(publication?.channelId===channel&&!publication.enabled)throw Error('A withdrawn publication needs a new channel');publication={channelId:channel,pageId:page,sourceVersion:4,enabled:true,artifactDigest:digest,snapshotId:source.snapshotId,publishedAt:'2026-10-10T09:00:00Z'}},withdraw:async()=>{publication.enabled=false},
inbox:async(_signal,_before,view='open')=>{if(mode==='failure')throw Error('Inbox is unavailable. Please refresh.');const all=mode==='empty'?[]:data;return{inquiries:all.filter(r=>view==='done'?r.status==='done':r.status!=='done'),nextBefore:null,counts:{open:all.filter(r=>r.status!=='done').length,done:all.filter(r=>r.status==='done').length}}},changeInquiry:async(item,operation,actionId,note)=>{const r=data.find(r=>r.requestId===item.requestId);if(mode==='save-failure')throw Error('We could not confirm the update. Refresh to check its status.');if(r.revision!==item.revision)throw Error('This inquiry changed. Refresh before trying again.');if(operation==='note')r.note=note;else{r.status=operation==='claim'?'in_progress':operation==='complete'?'done':'new';r.assignedTo=r.status==='new'?null:id}r.revision++;r.updatedBy=id;r.updatedAt=new Date().toISOString();return{...r,actionId}}}},[mode]);
return <div className="qa-layout"><aside><strong>›_ SUPERMEGA</strong><nav><button aria-current={view==='publish'?'page':undefined} onClick={()=>setView('publish')}>Website</button><button aria-current={view==='inbox'?'page':undefined} onClick={()=>setView('inbox')}>Inquiries <span>3</span></button></nav><small>Corner Café<br/>Synthetic QA workspace</small></aside><main className="website-product">{view==='publish'?<HostedSitePanel key={mode} client={client} snapshotId={source.snapshotId} pageId="contact" canWrite/>:<HostedInquiryInbox key={mode} client={client} actorId={id} canWrite={mode!=='view-only'}/>}<footer className="qa-controls">Synthetic QA controls {['received','empty','failure','save-failure','view-only'].map(m=><button onClick={()=>setMode(m)} key={m}>{m}</button>)}</footer></main></div>}
createRoot(document.getElementById('root')).render(<App/>);
` }, bundle: true, jsx: 'automatic', format: 'esm', define: { 'import.meta.env': '{}', 'process.env.NODE_ENV': '"development"' }, outfile: resolve(out, 'hosting.js') })
writeFileSync(resolve(out, 'hosting.html'), `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'self'; connect-src 'none'; form-action 'none'; base-uri 'none'; style-src 'self' 'unsafe-inline'"><title>Sites hosting — synthetic QA</title><link rel="stylesheet" href="hosting.css"><style>*{box-sizing:border-box}body{margin:0;background:#fafbfe;font-family:Inter,Arial,sans-serif;color:#161b30}.qa-layout{display:grid;grid-template-columns:210px minmax(0,1fr);min-height:100vh}.qa-layout>aside{padding:30px 18px;border-right:1px solid #e7e9f1;background:white;display:flex;flex-direction:column;gap:48px}.qa-layout>aside>strong{font-size:13px;letter-spacing:1px}.qa-layout nav{display:grid;gap:12px}.qa-layout nav button{background:white;border:0;border-radius:8px;padding:14px;text-align:left;color:#556079;font:inherit;cursor:pointer}.qa-layout nav button[aria-current]{background:#eeebff;color:#5541d5}.qa-layout nav span{float:right}.qa-layout aside small{margin-top:auto;color:#8690a5;line-height:1.8}.qa-layout>main{padding:40px;min-width:0}.qa-controls{margin-top:48px;padding:14px;background:#fff5da;font-size:12px;display:flex;gap:12px;flex-wrap:wrap}.qa-controls button{background:white;border:1px solid #ddd;border-radius:5px;padding:7px 12px}@media(max-width:750px){.qa-layout{grid-template-columns:1fr}.qa-layout>aside{padding:18px;gap:18px;border-right:0;border-bottom:1px solid #e7e9f1}.qa-layout aside small{display:none}.qa-layout nav{display:flex}.qa-layout>main{padding:24px 16px}.qa-layout nav button{min-width:140px}}</style><div id="root"></div><script type="module" src="hosting.js"></script></html>`)
console.log(resolve(out, 'hosting.html'))
