// Local visual acceptance harness: actual editor/model/preview/export, synthetic
// in-memory media transport. Never copied to production or used as marketing art.
import { createRequire } from 'node:module'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const { build } = createRequire(resolve(root, 'showroom/package.json'))('esbuild')
const out = resolve(root, '.tmp/qa-workspaces')
mkdirSync(out, { recursive: true })
await build({ stdin: { resolveDir: resolve(root, 'showroom'), loader: 'tsx', contents: `
import React,{useMemo,useState} from 'react';import {createRoot} from 'react-dom/client';
import {ContentWorkspace} from './src/products/website/ContentWorkspace';
import {SitePreview} from './src/products/website/SitePreview';
import {WebsiteMediaContext} from './src/products/website/WebsiteMediaContext';
import {createWebsiteMediaDownload} from './src/products/website/website-media-export';
import {createInitialWorkspace,applyWebsiteWorkspaceUpdate,createWebsitePreviewArtifact,restoreWorkspace} from './src/products/website/website-model';
import {applyWebsiteStarterBrief} from './src/products/website/website-starter';
import './src/core/core-app.css';import './src/products/website/website-product.css';
window.fetch=async()=>{throw Error('This fixture cannot access providers')};
const assets=new Map();
const initial=applyWebsiteStarterBrief(createInitialWorkspace(),{templateId:'lead-generation',businessName:'Corner Café',offer:'Fresh coffee and a place to pause',audience:'',proof:'',contactHref:''},'2026-10-10T00:00:00.000Z');
if(initial.siteName!=='Corner Café')throw Error('Synthetic starter did not apply');
function App(){const [saved,setSaved]=useState(initial),[draft,setDraft]=useState(initial),[editing,setEditing]=useState(false),[preview,setPreview]=useState(false),[fail,setFail]=useState(false),[notice,setNotice]=useState(''),[version,setVersion]=useState(0);
const client=useMemo(()=>({scopeKey:'synthetic-workspace',assertCurrent:async()=>{},upload:async(file,signal)=>{signal.throwIfAborted();if(fail)throw Error('Photo storage is unavailable. Your current image is unchanged.');if(file.type!=='image/webp')throw Error('This test uses the prepared WebP fixture.');const bytes=await file.arrayBuffer();const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');signal.throwIfAborted();const id=digest+'.webp';assets.set(id,new Blob([bytes],{type:'image/webp'}));return id},load:async(id,signal)=>{signal.throwIfAborted();if(fail||!assets.has(id))throw Error('Synthetic storage unavailable');return assets.get(id)}}),[fail]);
const media=useMemo(()=>({client,onEditingChange:setEditing}),[client]);
const page=draft.pages[0];const dirty=JSON.stringify(saved)!==JSON.stringify(draft);
async function download(){try{const result=await createWebsiteMediaDownload(createWebsitePreviewArtifact(saved),client,new AbortController().signal);const url=URL.createObjectURL(new Blob([result.content],{type:result.mimeType}));const link=document.createElement('a');link.href=url;link.download=result.filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),5000);setNotice('Downloaded saved pages with verified image bytes.')}catch(error){setNotice(error.message)}}
return <><aside className="qa-notice">LOCAL SYNTHETIC QA · actual Sites editor, preview and export · in-memory media transport · no login, provider upload or publishing</aside><div className="qa-shell"><nav className="qa-nav"><strong>SUPERMEGA</strong><a href="./">Products</a><span>Website</span></nav><main className="qa-content website-product"><WebsiteMediaContext.Provider value={media}><header className="photo-qa-heading"><div><h1>{preview?'Preview':'Edit page'}</h1><p>Make it yours. See the result as you work.</p></div><div className="website-image-actions"><button className="website-button is-secondary" onClick={()=>setPreview(v=>!v)}>{preview?'Back to editor':'Preview'}</button><button className="website-button is-primary" disabled={!dirty||editing} onClick={()=>{const result=applyWebsiteWorkspaceUpdate(saved,()=>draft);if(result.ok){setSaved(result.workspace);setDraft(result.workspace);setNotice('Page saved.')}}}>Save page</button></div></header>{notice?<p role="status">{notice}</p>:null}{preview?<SitePreview device="desktop" page={page} pages={draft.pages} siteName={draft.siteName} onSelectPage={()=>{}}/>:<ContentWorkspace key={version} page={page} canDuplicate={false} deleteArmed={false} onDuplicate={()=>{}} onRequestDelete={()=>{}} onUpdatePage={update=>setDraft(current=>({...current,pages:current.pages.map((p,i)=>i?p:update(p))}))}/>}<footer className="photo-qa-controls"><strong>Synthetic test controls</strong><button onClick={()=>{setDraft(restoreWorkspace(JSON.parse(JSON.stringify(saved))));setVersion(v=>v+1);setNotice('Reopened saved content.')}}>Reopen saved content</button><button onClick={()=>void download()}>Download saved website</button><label><input type="checkbox" checked={fail} onChange={e=>setFail(e.target.checked)}/>Simulate storage failure</label><output>{'Saved revision '+saved.contentRevision+' · '+assets.size+' test asset(s)'}</output></footer></WebsiteMediaContext.Provider></main></div></>}
createRoot(document.getElementById('root')).render(<App/>);
` }, bundle: true, jsx: 'automatic', format: 'esm', define: { 'import.meta.env': '{}', 'process.env.NODE_ENV': '"development"' }, outfile: resolve(out, 'photos.js') })
writeFileSync(resolve(out, 'photos.html'), `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'self'; connect-src 'none'; img-src 'self' blob:; form-action 'none'; base-uri 'none'; style-src 'self' 'unsafe-inline'"><title>Sites photo workflow — synthetic QA</title><link rel="stylesheet" href="photos.css"><link rel="stylesheet" href="qa.css"><style>.photo-qa-heading{display:flex;justify-content:space-between;align-items:center;gap:24px;margin-bottom:28px}.photo-qa-heading h1{font-size:32px;margin:0}.photo-qa-heading p{color:#757589;margin:4px 0}.photo-qa-controls{margin-top:32px;padding:16px;display:flex;flex-wrap:wrap;gap:16px;background:#fff4d7;font-size:12px}.photo-qa-controls label{display:flex;align-items:center;gap:8px}.photo-qa-controls button{padding:8px;border:1px solid #ccc;border-radius:6px;background:white;color:#222}@media(max-width:650px){.photo-qa-heading{align-items:flex-start;flex-direction:column;gap:12px}.photo-qa-heading h1{font-size:28px}}</style><div id="root"></div><script type="module" src="photos.js"></script></html>`)
console.log(resolve(out, 'photos.html'))
