// One reviewed stylesheet, generated bindings for both rendering runtimes.
import { readFileSync, writeFileSync } from 'node:fs'
import { createHash } from 'node:crypto'
const css = readFileSync(new URL('../showroom/src/products/website/website-presentation.css', import.meta.url), 'utf8').replaceAll('\r\n', '\n')
const digest = createHash('sha256').update(css).digest('hex')
const outputs = [
  ['../showroom/src/products/website/website-presentation.ts', `// Generated by tools/sync_website_presentation.mjs; edit website-presentation.css.\nexport const WEBSITE_PRESENTATION_DIGEST = '${digest}'\nexport const WEBSITE_PUBLIC_CSS = ${JSON.stringify(css)}\n`],
  ['../supermega_runtime/website_presentation.py', `# Generated by tools/sync_website_presentation.mjs; edit website-presentation.css.\nWEBSITE_PRESENTATION_DIGEST = '${digest}'\nWEBSITE_PUBLIC_CSS = ${JSON.stringify(css)}\n`],
]
for (const [path, text] of outputs) {
  const url = new URL(path, import.meta.url)
  if (process.argv.includes('--write')) writeFileSync(url, text)
  else if (readFileSync(url, 'utf8').replaceAll('\r\n', '\n') !== text) throw Error(`Sites presentation binding is stale: ${path}`)
}
console.log(JSON.stringify({ ok: true, digest, mode: process.argv.includes('--write') ? 'write' : 'check' }))
